### ISSUE TITLE
NEI Issue

### ISSUE THREAD

**Issue by Simon04090** [Inventory-Tweaks/inventory-tweaks#130]
When I check up a receipe in NEI it says:
"[ERROR] Failed to move picked up stack: Section not available (l36 in ContainerSectionManager.java)"
and throws this:
"[15:04:11 INFO]: Client> 2014-01-25 15:04:11 [Information] [STDERR]    at invtweaks.InvTweaksContainerSectionManager.<init>(InvTweaksContainerSectionManager.java:36)
[15:04:11 INFO]: Client> 2014-01-25 15:04:11 [Information] [STDERR]     at invtweaks.InvTweaksContainerSectionManager.<init>(InvTweaksContainerSectionManager.java:24)
[15:04:11 INFO]: Client> 2014-01-25 15:04:11 [Information] [STDERR]     at invtweaks.InvTweaks.onItemPickup(InvTweaks.java:203)
[15:04:11 INFO]: Client> 2014-01-25 15:04:11 [Information] [STDERR]     at invtweaks.InvTweaks.onTick(InvTweaks.java:430)
[15:04:11 INFO]: Client> 2014-01-25 15:04:11 [Information] [STDERR]     at invtweaks.InvTweaks.onTickInGUI(InvTweaks.java:133)
[15:04:11 INFO]: Client> 2014-01-25 15:04:11 [Information] [STDERR]     at invtweaks.forge.ForgeClientTick.tickEnd(ForgeClientTick.java:43)
[15:04:11 INFO]: Client> 2014-01-25 15:04:11 [Information] [STDERR]     at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
[15:04:11 INFO]: Client> 2014-01-25 15:04:11 [Information] [STDERR]     at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:141)
[15:04:11 INFO]: Client> 2014-01-25 15:04:11 [Information] [STDERR]     at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:367)
[15:04:11 INFO]: Client> 2014-01-25 15:04:11 [Information] [STDERR]     at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1970)
[15:04:11 INFO]: Client> 2014-01-25 15:04:11 [Information] [STDERR]     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
[15:04:11 INFO]: Client> 2014-01-25 15:04:11 [Information] [STDERR]     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
[15:04:11 INFO]: Client> 2014-01-25 15:04:11 [Information] [STDERR]     at net.minecraft.client.main.Main.main(SourceFile:101)
[15:04:11 INFO]: Client> 2014-01-25 15:04:11 [Information] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:04:11 INFO]: Client> 2014-01-25 15:04:11 [Information] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[15:04:11 INFO]: Client> 2014-01-25 15:04:11 [Information] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:04:11 INFO]: Client> 2014-01-25 15:04:11 [Information] [STDERR]     at java.lang.reflect.Method.invoke(Unknown Source)
[15:04:11 INFO]: Client> 2014-01-25 15:04:11 [Information] [STDERR]     at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
[15:04:11 INFO]: Client> 2014-01-25 15:04:11 [Information] [STDERR]     at net.minecraft.launchwrapper.Launch.main(Launch.java:27)"
inthe log.

**Comment by Kobata** [comment]
NEI doesn't give access to the inventory in the recipe screens, so any operation trying to mess with the inventory fails.

In this case, it's sort-on-pickup failing. There is nothing to be done about this, the message is correct.
