### ISSUE TITLE
1.7.2 Crash

### ISSUE THREAD

**Issue by TheTactAssassin** [Inventory-Tweaks/inventory-tweaks#146]

**Comment by TheTactAssassin** [comment]
Whenever I try to play Minecraft with this mod installed it crashes. Not sure if I'm doing something wrong or what.

**Comment by Kobata** [comment]
Please post the crash logs and information about Minecraft version and all installed mods with crash reports.

**Comment by TheTactAssassin** [comment]
I am running Minecraft Forge Version 1.7.2, and using TooManyItems (Forge) version 1.7.2, Treecapitator (Universal) Version 1.7.2.r01, and bspkrsCor (Universal) Version 6.0 (1.7.2).

---- Minecraft Crash Report ----
// Oops.

Time: 3/1/14 8:37 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.ClassNotFoundException: invtweaks.forge.ClientProxy
    at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:76)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:515)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:209)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:188)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:484)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:201)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:498)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:853)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: invtweaks.forge.ClientProxy
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:188)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at cpw.mods.fml.common.ModClassLoader.loadClass(ModClassLoader.java:58)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:59)
    ... 33 more
Caused by: java.lang.NoClassDefFoundError: cpw/mods/fml/common/IPickupNotifier
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:180)
    ... 39 more
Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.common.IPickupNotifier
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:188)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 43 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:180)
    ... 45 more

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 8 (x86) version 6.2
    Java Version: 1.7.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode, sharing), Oracle Corporation
    Memory: 33853296 bytes (32 MB) / 153739264 bytes (146 MB) up to 518979584 bytes (494 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.01-pre FML v7.2.125.1034 Minecraft Forge 10.12.0.1034 7 mods loaded, 7 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed
    FML{7.2.125.1034} [Forge Mod Loader](forge-1.7.2-10.12.0.1034.jar) Unloaded->Constructed
    Forge{10.12.0.1034} [Minecraft Forge](forge-1.7.2-10.12.0.1034.jar) Unloaded->Constructed
    bspkrsCore{6.0(1.7.2)} [bspkrsCore]([1.7.2]bspkrsCore-universal-6.0%281.7.2%29.jar) Unloaded->Constructed
    TreeCapitator{1.7.2.r01} [TreeCapitator]([1.7.2]TreeCapitator-universal-1.7.2.r01.jar) Unloaded->Constructed
    inventorytweaks{1.56} [Inventory Tweaks](InventoryTweaks-MC1.6.2-1.56-b77.jar) Unloaded->Errored
    TooManyItems{1.7.2} [TooManyItems](TooManyItems2014_01_13_1.7.2_Forge%281%29.jar) Unloaded->Constructed

**Comment by Kobata** [comment]
That is a 1.6 version of InvTweaks, not a 1.7 version.

**Comment by TheTactAssassin** [comment]
OK thanks for the help.
