### ISSUE TITLE
Crash InvTweaks config with Biomes O'Plenty

### ISSUE THREAD

**Issue by knave2000** [Inventory-Tweaks/inventory-tweaks#153]
BiomesOPlenty-1.7.2-2.0.0.714-universal and InventoryTweaks-1.57-116 doesn't work together with default settings. Some problem with config.

Without BoP works fine.

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 16.03.14 15:40
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.Error: InvTweaks config load failed
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:677)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:260)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:556)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:850)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.Error: InvTweaks config load failed
    at invtweaks.InvTweaksConfigManager.loadConfig(InvTweaksConfigManager.java:187)
    at invtweaks.InvTweaksConfigManager.makeSureConfigurationIsLoaded(InvTweaksConfigManager.java:59)
    at invtweaks.InvTweaks.<init>(InvTweaks.java:105)
    at invtweaks.forge.ClientProxy.init(ClientProxy.java:40)
    at invtweaks.forge.InvTweaksMod.init(InvTweaksMod.java:36)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:536)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:209)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:188)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:676)
    ... 10 more
Caused by: java.lang.NullPointerException
    at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:231)
    at invtweaks.InvTweaksItemTree.registerOre(InvTweaksItemTree.java:327)
    at invtweaks.InvTweaksItemTreeLoader.startElement(InvTweaksItemTreeLoader.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
    at javax.xml.parsers.SAXParser.parse(Unknown Source)
    at invtweaks.InvTweaksItemTreeLoader.load(InvTweaksItemTreeLoader.java:51)
    at invtweaks.InvTweaksConfig.load(InvTweaksConfig.java:106)
    at invtweaks.InvTweaksConfigManager.loadConfig(InvTweaksConfigManager.java:175)
    ... 40 more
Caused by: java.lang.NullPointerException
    at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:231)
    at invtweaks.InvTweaksItemTree.registerOre(InvTweaksItemTree.java:327)
    at invtweaks.InvTweaksItemTreeLoader.startElement(InvTweaksItemTreeLoader.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
    at javax.xml.parsers.SAXParser.parse(Unknown Source)
    at invtweaks.InvTweaksItemTreeLoader.load(InvTweaksItemTreeLoader.java:51)
    at invtweaks.InvTweaksConfig.load(InvTweaksConfig.java:106)
    at invtweaks.InvTweaksConfigManager.loadConfig(InvTweaksConfigManager.java:143)
    ... 40 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.7.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 45620056 bytes (43 MB) / 220114944 bytes (209 MB) up to 1037959168 bytes (989 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.01-pre FML v7.2.116.1025 Minecraft Forge 10.12.0.1025 Optifine OptiFine_1.7.2_HD_U_C2 19 mods loaded, 19 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FML{7.2.116.1025} [Forge Mod Loader](forge-1.7.2-10.12.0.1025.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Forge{10.12.0.1025} [Minecraft Forge](forge-1.7.2-10.12.0.1025.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TooManyItems{1.7.2} [TooManyItems](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiomesOPlenty{2.0.0} [Biomes O' Plenty](010_BiomesOPlenty-1.7.2-2.0.0.714-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    inventorytweaks{1.57-116} [Inventory Tweaks](035_InventoryTweaks-1.57-116.jar) Unloaded->Constructed->Pre-initialized->Errored
    bspkrsCore{6.0(1.7.2)} [bspkrsCore](055_[1.7.2]bspkrscore-universal-6.0%281.7.2%29.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ArmorStatusHUD{1.18(1.7.2)} [ArmorStatusHUD](050_[1.7.2]ArmorStatusHUD-client-1.18%281.7.2%29.jar) Unloaded->Constructed->Pre-initialized->Initialized
    WorldStateCheckpoints{1.7.2.r01} [WorldStateCheckpoints](057_[1.7.2]WorldStateCheckpoints-client-1.7.2.r01.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DirectionHUD{1.18(1.7.2)} [DirectionHUD](060_[1.7.2]DirectionHUD-client-1.18%281.7.2%29.jar) Unloaded->Constructed->Pre-initialized->Initialized
    StatusEffectHUD{1.21(1.7.2)} [StatusEffectHUD](075_[1.7.2]StatusEffectHUD-client-1.21%281.7.2%29.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Core{5.0.3} [BuildCraft](100_buildcraft-5.0.3.61.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Builders{5.0.3} [BC Builders](100_buildcraft-5.0.3.61.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Energy{5.0.3} [BC Energy](100_buildcraft-5.0.3.61.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Factory{5.0.3} [BC Factory](100_buildcraft-5.0.3.61.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Transport{5.0.3} [BC Transport](100_buildcraft-5.0.3.61.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Silicon{5.0.3} [BC Silicon](100_buildcraft-5.0.3.61.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CustomSpawner{3.2.0.dev.R1} [DrZhark's CustomSpawner](255_CustomMobSpawner_3.2.0-DEV-R1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MoCreatures{6.2.0.dev.R1} [DrZhark's Mo'Creatures Mod](265_DrZharks MoCreatures Mod v6.2.0-DEV-R1.jar) Unloaded->Constructed->Pre-initialized->Initialized

**Comment by Kobata** [comment]
As far as I can tell they seem to be registering an ore with no item, so I'd call it _probably_ BOP's issue.

**Comment by eyamaz** [comment]
not sure on that. Adubbz said they are not, but he thinks it might have to do with the warning screen they are adding to launch.

**Comment by Kobata** [comment]
Well, some mod there is:

```
Caused by: java.lang.NullPointerException
at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:231)
at invtweaks.InvTweaksItemTree.registerOre(InvTweaksItemTree.java:327)
```

The MC function there (this is where it's really crashing, the other exception is just a wrapper) is ItemStack.getItemDamage.
It's being called from my [OreDict handler](https://github.com/Kobata/inventory-tweaks/blob/develop/src/main/java/invtweaks/InvTweaksItemTree.java#L325), which just finds all items registered to an OreDict tag and looks at them. (Notice the ItemStack used is from iterating the list, so it's the same one given by the mod to Forge)

Without a full debug setup or blindly testing by editing the configs I can't tell you _which_ item this is, but the ones referenced in the default config are only very common metals and the entries that exist for MC default items.

[BOP's code for adding to the OreDict](https://github.com/Glitchfiend/BiomesOPlenty/blob/master/src/main/java/biomesoplenty/common/core/BOPCrafting.java#L330) looks rather suspicious because it's creating ItemStacks from direct lookups which could potentially be null depending on timing/if things are disabled in the config/typos/any other issue that could cause the lookup to fail.

There's some other mods listed in the report, so it could also be one of those, but I would expect someone trying to blame it on a specific mod to have tested adding/removing that mod at least.

**Comment by eyamaz** [comment]
I've tested it and I know for a fact its between InvTw and BoP. I'll try to pass this to them to see if thats the problem then.

**Comment by Adubbz** [comment]
It's not possible for those Ore Dict entries to be null without a typo, as we don't allow items/blocks to be disabled removing their IDs, only their recipes (and even then, that's only for certain things).

**Comment by Kobata** [comment]
Well, quick debugging shows it failing at "stairWood"

The contents of the OreDictionary list for that:
`[0] = {net.minecraft.item.ItemStack@5453}"1xtile.stairsWood@0"
[1] = {net.minecraft.item.ItemStack@5454}"1xtile.stairsWoodSpruce@0"
[2] = {net.minecraft.item.ItemStack@5455}"1xtile.stairsWoodBirch@0"
[3] = {net.minecraft.item.ItemStack@5456}"1xtile.stairsWoodJungle@0"
[4] = {net.minecraft.item.ItemStack@5457}"1xtile.stairsWoodAcacia@0"
[5] = {net.minecraft.item.ItemStack@5458}"1xtile.stairsWoodDarkOak@0"
[6] = {net.minecraft.item.ItemStack@5459}"1xtile.redwoodStairs@0"
[7] = {net.minecraft.item.ItemStack@5460}"1xtile.willowStairs@0"
[8] = {net.minecraft.item.ItemStack@4622}Method threw 'java.lang.NullPointerException' exception. Cannot evaluate net.minecraft.item.ItemStack.toString()
[9] = {net.minecraft.item.ItemStack@5461}"1xtile.firStairs@0"
[10] = {net.minecraft.item.ItemStack@5462}"1xtile.cherryStairs@0"
[11] = {net.minecraft.item.ItemStack@5463}"1xtile.darkStairs@0"
[12] = {net.minecraft.item.ItemStack@5464}"1xtile.magicStairs@0"
[13] = {net.minecraft.item.ItemStack@5465}"1xtile.palmStairs@0"
[14] = {net.minecraft.item.ItemStack@5466}"1xtile.mangroveStairs@0"
[15] = {net.minecraft.item.ItemStack@5467}"1xtile.holyStairs@0"
[16] = {net.minecraft.item.ItemStack@5468}"1xtile.pineStairs@0"
[17] = {net.minecraft.item.ItemStack@5469}"1xtile.hellBarkStairs@0"
[18] = {net.minecraft.item.ItemStack@5470}"1xtile.jacarandaStairs@0"
[19] = {net.minecraft.item.ItemStack@5471}"1xtile.mahoganyStairs@0"`

Since that _seems_ to be in order, probably this line: `OreDictionary.registerOre("stairWood", new ItemStack(BOPBlockHelper.get("acaciaStairs")));`

**Comment by Adubbz** [comment]
Yup, you're right, seems Forstride forgot to change them to Sacred Oak when he was replacing Acacia wood.

**Comment by Adubbz** [comment]
This should now be fixed in the latest build of BoP (718+)

**Comment by joshuafcole** [comment]
I am running into the same issue _without BoP installed_. Do you have a copy of InvTweaks with debugging enabled so I can figure out which mod is causing the issue? I have a hunch it's either OresPlus or Natura, but I don't have an easy way figure that out.

Side note: I'd never realized how much I'd come to rely on InvTweaks until I couldn't use it. Thanks for the great mod!

Crashlog:
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 5/25/14 11:55 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.Error: InvTweaks config load failed
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:688)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:527)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:815)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.Error: InvTweaks config load failed
    at invtweaks.InvTweaksConfigManager.loadConfig(InvTweaksConfigManager.java:187)
    at invtweaks.InvTweaksConfigManager.makeSureConfigurationIsLoaded(InvTweaksConfigManager.java:59)
    at invtweaks.InvTweaks.<init>(InvTweaks.java:105)
    at invtweaks.forge.ClientProxy.init(ClientProxy.java:40)
    at invtweaks.forge.InvTweaksMod.init(InvTweaksMod.java:37)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:687)
    ... 10 more
Caused by: java.lang.NullPointerException
    at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:214)
    at invtweaks.InvTweaksItemTree.registerOre(InvTweaksItemTree.java:327)
    at invtweaks.InvTweaksItemTreeLoader.startElement(InvTweaksItemTreeLoader.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
    at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1342)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2770)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:333)
    at javax.xml.parsers.SAXParser.parse(SAXParser.java:328)
    at invtweaks.InvTweaksItemTreeLoader.load(InvTweaksItemTreeLoader.java:51)
    at invtweaks.InvTweaksConfig.load(InvTweaksConfig.java:106)
    at invtweaks.InvTweaksConfigManager.loadConfig(InvTweaksConfigManager.java:175)
    ... 40 more
Caused by: java.lang.NullPointerException
    at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:214)
    at invtweaks.InvTweaksItemTree.registerOre(InvTweaksItemTree.java:327)
    at invtweaks.InvTweaksItemTreeLoader.startElement(InvTweaksItemTreeLoader.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
    at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1342)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2770)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:333)
    at javax.xml.parsers.SAXParser.parse(SAXParser.java:328)
    at invtweaks.InvTweaksItemTreeLoader.load(InvTweaksItemTreeLoader.java:51)
    at invtweaks.InvTweaksConfig.load(InvTweaksConfig.java:106)
    at invtweaks.InvTweaksConfigManager.loadConfig(InvTweaksConfigManager.java:143)
    ... 40 more

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Linux (amd64) version 3.11.0-20-generic
    Java Version: 1.8.0_05, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 164381904 bytes (156 MB) / 693108736 bytes (661 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 2 total; -Xmx4096m -XX:MaxPermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.03 FML v7.2.196.1087 Minecraft Forge 10.12.1.1087 46 mods loaded, 46 mods active
    mcp{9.03} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FML{7.2.196.1087} [Forge Mod Loader](modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Forge{10.12.1.1087} [Minecraft Forge](modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AppliedEnergistics2-Core{rv0-beta-11} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CodeChickenCore{1.0.0} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NotEnoughItems{1.0.1} [Not Enough Items](NotEnoughItems-1.7.2-1.0.1-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    PlayerAPI{1.4} [Player API](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    SmartCore{1.0} [Smart Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TConstruct-Preloader{0.1.1} [Tinkers Corestruct](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    bspkrsCore{6.9} [bspkrsCore]([1.7.2]bspkrsCore-universal-6.9.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ArmorStatusHUD{1.26} [ArmorStatusHUD]([1.7.2]ArmorStatusHUD-client-1.26.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DamageIndicatorsMod{3.1.1} [Damage Indicators]([1.7.2]DamageIndicatorsMod-3.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    StatusEffectHUD{1.25} [StatusEffectHUD]([1.7.2]StatusEffectHUD-client-1.25.jar) Unloaded->Constructed->Pre-initialized->Initialized
    IC2{2.1.477-experimental} [IndustrialCraft 2](industrialcraft-2-2.1.477-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized
    appliedenergistics2{rv0-beta-11} [Applied Energistics 2](appliedenergistics2-rv0-beta-11.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ArchimedesShips{1.7.2 v1.5.2} [Archimedes' Ships](ArchimedesShips.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BattleTowers{1.4.6} [Battle Towers](BattleTowers-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioCraft{1.7.0} [BiblioCraft](BiblioCraft[1.7.0][MC1.7.2].jar) Unloaded->Constructed->Pre-initialized->Initialized
    AWWayofTime{v1.0.1e} [Blood Magic: Alchemical Wizardry](Blood Magic-v1.0.1e.jar) Unloaded->Constructed->Pre-initialized->Initialized
    craftingpillars{1.5.0} [Crafting Pillars Mod](CraftingPillars-MC1.7.2-1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    eplus{1.7.2-2.0.1.6} [Enchanting Plus](EnchantingPlus-1.7.2-2.0.1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Baubles{1.0.0.13} [Baubles](Baubles-1.7.2-1.0.0.13.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Thaumcraft{4.1.1.14} [Thaumcraft](Thaumcraft-1.7.2-4.1.1.14.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Highlands{2.2.0pre3} [Highlands](Highlands-1.7.2-v-2.2.0pre4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    HopperDuctMod{1.3} [Hopper Ducts](hopperductmod-1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    inventorytweaks{1.58-dev-124} [Inventory Tweaks](InventoryTweaks-1.58-dev-124.jar) Unloaded->Constructed->Pre-initialized->Errored
    IronChest{6.0.14.719} [Iron Chest](ironchest-1.7.2-6.0.14.719-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Mantle{1.7.2-132.45b0b50} [Mantle](Mantle-1.7.2-0.2.8.jar) Unloaded->Constructed->Pre-initialized->Initialized
    moreNature{0.6.1} [More Nature](morenature-0.6.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Mystcraft{@VERSION@} [Mystcraft](mystcraft-1.7.2-0.10.14.00.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Natura{2.2.0} [Natura](natura-1.7.2-2.2.0a3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OresPlus{0.6.36 Beta} [OresPlus](OresPlus-0.6.33_Beta.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Railcraft{9.0.0.0} [Railcraft](Railcraft_1.7.2-9.0.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Roguelike{1.3.0} [Roguelike Dungeons](roguelike-1.7.2-1.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized
    shipwrecks_winslow{1.6.2} [Shipwrecks!](shipwrecks_winslow-1.7.2-1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    SmartMoving{15.0} [Smart Moving](SmartMoving-1.7.2-15.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    SmartRender{2.0} [Smart Render](SmartRender-1.7.2-2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TConstruct{1.7.2-1.6.0.jenkins478} [Tinkers' Construct](TConstruct-1.7.2-1.6.0.a14.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TMechworks{1.7.2-60.0ab3ef0} [Tinkers' Mechworks](TMechworks-1.7.2-0.2.7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TwilightForest{2.0.3} [The Twilight Forest](twilightforest-1.7.2-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AS_UpdateCheck{1.1.5} [AtomicStryker Update Check Mod](UpdateCheckerMod-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    VillageMods{1.7.2-1.3} [Village Mods](villagemods-1.7.2-1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    VillageBiomes{${version}} [Village Biomes](villagemods-1.7.2-1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    VillageDensity{${version}} [Village Density](villagemods-1.7.2-1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    voxelmap{1.7.2} [VoxelMap](voxelmap-1.7.2-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    YALSM{2.1.3} [Yet Another Leather Smelting Mod](yalsm-2.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AE2 Version: beta rv0-beta-11 for Forge 10.12.0.1024
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.

**Comment by joshuafcole** [comment]
Poking around I found issue #160 and tried removing Crafting Pillars for kicks -- Crafting Pillars was the issue. Since I don't rely on it that's good enough for me, but it would be good to have richer debugging information in the log for this (apparently somewhat common) error if possible.
