### ISSUE TITLE
Immediate Crash on v1.7.2

### ISSUE THREAD

**Issue by DRockLee** [Inventory-Tweaks/inventory-tweaks#157]
This is the crash report on staring the game...
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 3/22/14 10:28 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.Error: InvTweaks config load failed
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:674)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:267)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:559)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:853)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.Error: InvTweaks config load failed
    at invtweaks.InvTweaksConfigManager.loadConfig(InvTweaksConfigManager.java:187)
    at invtweaks.InvTweaksConfigManager.makeSureConfigurationIsLoaded(InvTweaksConfigManager.java:59)
    at invtweaks.InvTweaks.<init>(InvTweaks.java:105)
    at invtweaks.forge.ClientProxy.init(ClientProxy.java:40)
    at invtweaks.forge.InvTweaksMod.init(InvTweaksMod.java:36)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:209)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:188)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:673)
    ... 10 more
Caused by: java.lang.NullPointerException
    at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:231)
    at invtweaks.InvTweaksItemTree.registerOre(InvTweaksItemTree.java:327)
    at invtweaks.InvTweaksItemTreeLoader.startElement(InvTweaksItemTreeLoader.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
    at javax.xml.parsers.SAXParser.parse(Unknown Source)
    at invtweaks.InvTweaksItemTreeLoader.load(InvTweaksItemTreeLoader.java:51)
    at invtweaks.InvTweaksConfig.load(InvTweaksConfig.java:106)
    at invtweaks.InvTweaksConfigManager.loadConfig(InvTweaksConfigManager.java:175)
    ... 40 more
Caused by: java.lang.NullPointerException
    at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:231)
    at invtweaks.InvTweaksItemTree.registerOre(InvTweaksItemTree.java:327)
    at invtweaks.InvTweaksItemTreeLoader.startElement(InvTweaksItemTreeLoader.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
    at javax.xml.parsers.SAXParser.parse(Unknown Source)
    at invtweaks.InvTweaksItemTreeLoader.load(InvTweaksItemTreeLoader.java:51)
    at invtweaks.InvTweaksConfig.load(InvTweaksConfig.java:106)
    at invtweaks.InvTweaksConfigManager.loadConfig(InvTweaksConfigManager.java:143)
    ... 40 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 47576696 bytes (45 MB) / 478674944 bytes (456 MB) up to 954728448 bytes (910 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.01-pre FML v7.2.129.1047 Minecraft Forge 10.12.0.1047 13 mods loaded, 13 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FML{7.2.129.1047} [Forge Mod Loader](forge-1.7.2-10.12.0.1047.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Forge{10.12.0.1047} [Minecraft Forge](forge-1.7.2-10.12.0.1047.jar) Unloaded->Constructed->Pre-initialized->Initialized
    bspkrsCore{6.0(1.7.2)} [bspkrsCore]([1.7.2]bspkrsCore-universal-6.0%281.7.2%29.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TreeCapitator{1.7.2.r01} [TreeCapitator]([1.7.2]TreeCapitator-universal-1.7.2.r01.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiomesOPlenty{2.0.0} [Biomes O' Plenty](BiomesOPlenty-1.7.2-2.0.0.687-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    HardcoreEnderExpansion{1.5-BETA} [Hardcore Ender Expansion](HardcoreEnderExpansion.jar) Unloaded->Constructed->Pre-initialized->Errored
    IC2{2.1.430-experimental} [IndustrialCraft 2](industrialcraft-2_2.1.430-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized
    inventorytweaks{1.57-116} [inventorytweaks](InventoryTweaks-1.57-116.jar) Unloaded->Constructed->Pre-initialized->Errored
    IronChest{6.0.11.717} [Iron Chest](ironchest-1.7.2-6.0.11.717-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    millenaire{5.2.0b1} [Millénaire](millenaire-5.2b1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TwilightForest{2.0.3} [The Twilight Forest](twilightforest-1.7.2-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    wildcaves3{0.4.3.6(1.7.2)} [Wild Caves 3](WildCaves3-0.4.3.6%281.7.2%29.jar) Unloaded->Constructed->Pre-initialized->Initialized

**Comment by Kobata** [comment]
Duplicate #153, update BOP.
