### ISSUE TITLE
Inv Tweaks bug with NEI

### ISSUE THREAD

**Issue by Yascob99** [Inventory-Tweaks/inventory-tweaks#159]
Version: InventoryTweaks-MC1.6.2-1.56-b77
OS: Mac OSX 10.9.2
       Processor: 2.66 GHz Intel Core i7
       RAM: (2x4GB)8 GB 1067 MHz DDR3
       VRAM(Graphics card): NVIDIA GeForce GT 330M 512 MB
Whenever I check an Item's recipe in recipe mod on NEI(v1.6.1.8) it gives me this message:

InvTweaks: [ERROR] Failed to move picked up stack: Section not available (l36 in ContainerSectionManager.java)

Heres the code of the error:

[17:10:28 INFO]: Client> 2014-03-25 17:10:28 [INFO] [STDERR] java.lang.Exception: Section not available
[17:10:28 INFO]: Client> 2014-03-25 17:10:28 [INFO] [STDERR]    at invtweaks.InvTweaksContainerSectionManager.<init>(InvTweaksContainerSectionManager.java:36)
[17:10:28 INFO]: Client> 2014-03-25 17:10:28 [INFO] [STDERR]    at invtweaks.InvTweaksContainerSectionManager.<init>(InvTweaksContainerSectionManager.java:24)
[17:10:28 INFO]: Client> 2014-03-25 17:10:28 [INFO] [STDERR]    at invtweaks.InvTweaks.onItemPickup(InvTweaks.java:203)
[17:10:28 INFO]: Client> 2014-03-25 17:10:28 [INFO] [STDERR]    at invtweaks.InvTweaks.onTick(InvTweaks.java:430)
[17:10:28 INFO]: Client> 2014-03-25 17:10:28 [INFO] [STDERR]    at invtweaks.InvTweaks.onTickInGUI(InvTweaks.java:133)
[17:10:28 INFO]: Client> 2014-03-25 17:10:28 [INFO] [STDERR]    at invtweaks.forge.ForgeClientTick.tickEnd(ForgeClientTick.java:43)
[17:10:28 INFO]: Client> 2014-03-25 17:10:28 [INFO] [STDERR]    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
[17:10:28 INFO]: Client> 2014-03-25 17:10:28 [INFO] [STDERR]    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:141)
[17:10:28 INFO]: Client> 2014-03-25 17:10:28 [INFO] [STDERR]    at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:367)
[17:10:28 INFO]: Client> 2014-03-25 17:10:28 [INFO] [STDERR]    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1970)
[17:10:28 INFO]: Client> 2014-03-25 17:10:28 [INFO] [STDERR]    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
[17:10:28 INFO]: Client> 2014-03-25 17:10:28 [INFO] [STDERR]    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
[17:10:28 INFO]: Client> 2014-03-25 17:10:28 [INFO] [STDERR]    at net.minecraft.client.main.Main.main(SourceFile:101)
[17:10:28 INFO]: Client> 2014-03-25 17:10:28 [INFO] [STDERR]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:10:28 INFO]: Client> 2014-03-25 17:10:28 [INFO] [STDERR]    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[17:10:28 INFO]: Client> 2014-03-25 17:10:28 [INFO] [STDERR]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[17:10:28 INFO]: Client> 2014-03-25 17:10:28 [INFO] [STDERR]    at java.lang.reflect.Method.invoke(Method.java:597)
[17:10:28 INFO]: Client> 2014-03-25 17:10:28 [INFO] [STDERR]    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
[17:10:28 INFO]: Client> 2014-03-25 17:10:28 [INFO] [STDERR]    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

**Comment by Kobata** [comment]
NEI does not have the player inventory available in the recipe display screens, this is an expected error if an operation tries to run while those screens are open.
