### ISSUE TITLE
Crash Report w/ Crafting Pillars and Inventory Tweaks

### ISSUE THREAD

**Issue by Gathe3** [Inventory-Tweaks/inventory-tweaks#160]
I know I have some other mods installed too, but I'm sure that the incompatibility is between these two mods (I tested it): Inv Tweaks and Crafting Pillars. Can someone help me to fix it?

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 28/03/14 22:09
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.Error: InvTweaks config load failed
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:674)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:267)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:559)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:853)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.Error: InvTweaks config load failed
    at invtweaks.InvTweaksConfigManager.loadConfig(InvTweaksConfigManager.java:187)
    at invtweaks.InvTweaksConfigManager.makeSureConfigurationIsLoaded(InvTweaksConfigManager.java:59)
    at invtweaks.InvTweaks.<init>(InvTweaks.java:105)
    at invtweaks.forge.ClientProxy.init(ClientProxy.java:40)
    at invtweaks.forge.InvTweaksMod.init(InvTweaksMod.java:36)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:209)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:188)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:673)
    ... 10 more
Caused by: java.lang.NullPointerException
    at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:231)
    at invtweaks.InvTweaksItemTree.registerOre(InvTweaksItemTree.java:327)
    at invtweaks.InvTweaksItemTreeLoader.startElement(InvTweaksItemTreeLoader.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
    at javax.xml.parsers.SAXParser.parse(Unknown Source)
    at invtweaks.InvTweaksItemTreeLoader.load(InvTweaksItemTreeLoader.java:51)
    at invtweaks.InvTweaksConfig.load(InvTweaksConfig.java:106)
    at invtweaks.InvTweaksConfigManager.loadConfig(InvTweaksConfigManager.java:175)
    ... 40 more
Caused by: java.lang.NullPointerException
    at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:231)
    at invtweaks.InvTweaksItemTree.registerOre(InvTweaksItemTree.java:327)
    at invtweaks.InvTweaksItemTreeLoader.startElement(InvTweaksItemTreeLoader.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
    at javax.xml.parsers.SAXParser.parse(Unknown Source)
    at invtweaks.InvTweaksItemTreeLoader.load(InvTweaksItemTreeLoader.java:51)
    at invtweaks.InvTweaksConfig.load(InvTweaksConfig.java:106)
    at invtweaks.InvTweaksConfigManager.loadConfig(InvTweaksConfigManager.java:143)
    ... 40 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.7.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 71475504 bytes (68 MB) / 240590848 bytes (229 MB) up to 1037959168 bytes (989 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1024m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.01-pre FML v7.2.129.1047 Minecraft Forge 10.12.0.1047 13 mods loaded, 13 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FML{7.2.129.1047} [Forge Mod Loader](forge-1.7.2-10.12.0.1047.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Forge{10.12.0.1047} [Minecraft Forge](forge-1.7.2-10.12.0.1047.jar) Unloaded->Constructed->Pre-initialized->Initialized
    SC0_SpaceCore{0.7.6} [SpaceCore]([1.7.2] SpaceCore 0.7.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
    SC0_MorePotionTypes{1.0.2} [More Potion Types]([1.7.2] More Potion Types 1.0.2.zip) Unloaded->Constructed->Pre-initialized->Initialized
    bspkrsCore{6.0(1.7.2)} [bspkrsCore]([1.7.2]bspkrsCore-universal-6.0%281.7.2%29.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ArmorStatusHUD{1.18(1.7.2)} [ArmorStatusHUD]([1.7.2]ArmorStatusHUD-client-1.18%281.7.2%29.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CrystalWing{1.7.2.r01} [CrystalWing]([1.7.2]CrystalWing-universal-1.7.2.r01.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DamageIndicatorsMod{3.1.0} [Damage Indicators]([1.7.2]DamageIndicatorsMod-3.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FloatingRuins{1.7.2.r02} [FloatingRuins]([1.7.2]FloatingRuins-universal-1.7.2.r02.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiomesOPlenty{2.0.0} [Biomes O' Plenty](BiomesOPlenty-1.7.2-2.0.0.726-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    craftingpillars{1.5.0} [Crafting Pillars Mod](CraftingPillars-MC1.7.2-1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    inventorytweaks{1.57-116} [Inventory Tweaks](InventoryTweaks-1.57-116.jar) Unloaded->Constructed->Pre-initialized->Errored

**Comment by Kobata** [comment]
Looks more like #153 to me. Update BOP.

**Comment by Gathe3** [comment]
BOP is in version 2.0.0.726, is it a fixed one?

**Comment by Kobata** [comment]
I don't know what build they fixed in it, check the changelogs or ask them. If you do have a fixed version of BOP, refer whoever made the other mod you think did this to this report and the BOP one.

**Comment by TigersFangs** [comment]
I am using Minecraft 1.7.2. This instance has nothing but Forge 10.12.1.1110, Crafting Pillars v1.5, and InventoryTweaks v1.57-116. Out of 80+ mods, these are the only two that don't get along. I have run them in this isolated instance for a pure error report. The problem is that I don't understand how to fix it or which is causing it.

Any help would be greatly appreciated. Sorry to re-open a closed issue, but I thought that it would be better than opening a new one.

==================================Begin Error Log===================================

---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 6/3/14 10:35 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.Error: InvTweaks config load failed
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:527)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:815)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.Error: InvTweaks config load failed
    at invtweaks.InvTweaksConfigManager.loadConfig(InvTweaksConfigManager.java:187)
    at invtweaks.InvTweaksConfigManager.makeSureConfigurationIsLoaded(InvTweaksConfigManager.java:59)
    at invtweaks.InvTweaks.<init>(InvTweaks.java:105)
    at invtweaks.forge.ClientProxy.init(ClientProxy.java:40)
    at invtweaks.forge.InvTweaksMod.init(InvTweaksMod.java:36)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:690)
    ... 10 more
Caused by: java.lang.NullPointerException
    at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:214)
    at invtweaks.InvTweaksItemTree.registerOre(InvTweaksItemTree.java:327)
    at invtweaks.InvTweaksItemTreeLoader.startElement(InvTweaksItemTreeLoader.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
    at javax.xml.parsers.SAXParser.parse(Unknown Source)
    at invtweaks.InvTweaksItemTreeLoader.load(InvTweaksItemTreeLoader.java:51)
    at invtweaks.InvTweaksConfig.load(InvTweaksConfig.java:106)
    at invtweaks.InvTweaksConfigManager.loadConfig(InvTweaksConfigManager.java:175)
    ... 41 more
Caused by: java.lang.NullPointerException
    at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:214)
    at invtweaks.InvTweaksItemTree.registerOre(InvTweaksItemTree.java:327)
    at invtweaks.InvTweaksItemTreeLoader.startElement(InvTweaksItemTreeLoader.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
    at javax.xml.parsers.SAXParser.parse(Unknown Source)
    at invtweaks.InvTweaksItemTreeLoader.load(InvTweaksItemTreeLoader.java:51)
    at invtweaks.InvTweaksConfig.load(InvTweaksConfig.java:106)
    at invtweaks.InvTweaksConfigManager.loadConfig(InvTweaksConfigManager.java:143)
    ... 41 more

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 426119032 bytes (406 MB) / 1004011520 bytes (957 MB) up to 2077753344 bytes (1981 MB)
    JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:+AggressiveOpts -XX:+CMSClassUnloadingEnabled -XX:PermSize=128m -Xms1G -Xmx2G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.03 FML v7.2.207.1110 Minecraft Forge 10.12.1.1110 5 mods loaded, 5 mods active
    mcp{9.03} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FML{7.2.207.1110} [Forge Mod Loader](forge-1.7.2-10.12.1.1110.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Forge{10.12.1.1110} [Minecraft Forge](forge-1.7.2-10.12.1.1110.jar) Unloaded->Constructed->Pre-initialized->Initialized
    craftingpillars{1.5.0} [Crafting Pillars Mod]([1.7.2] CraftingPillars v1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    inventorytweaks{1.57-116} [Inventory Tweaks](InventoryTweaks-1.57-116.jar) Unloaded->Constructed->Pre-initialized->Errored
