### ISSUE TITLE
minecraft crash with inv.tweaks at 1.7.2

### ISSUE THREAD

**Issue by turocan** [Inventory-Tweaks/inventory-tweaks#166]
i dont know much about intall mods, but i did all the steps but when i run minecraft, it just open and closes the window.
Here is the crash report (I read it, but dont understand anything -.-) 

---- Minecraft Crash Report ----
// There are four lights!

Time: 18/05/14 12:59
Description: Initializing game

java.lang.NoSuchMethodError: com.google.common.collect.Multimaps.filterValues(Lcom/google/common/collect/SetMultimap;Lcom/google/common/base/Predicate;)Lcom/google/common/collect/SetMultimap;
    at cpw.mods.fml.common.discovery.ASMDataTable.getAnnotationsFor(ASMDataTable.java:109)
    at cpw.mods.fml.common.network.internal.NetworkModHolder.<init>(NetworkModHolder.java:91)
    at cpw.mods.fml.common.network.NetworkRegistry.register(NetworkRegistry.java:285)
    at cpw.mods.fml.common.FMLContainer.modConstruction(FMLContainer.java:77)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:207)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:186)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:117)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:487)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:194)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:495)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:849)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at cpw.mods.fml.common.discovery.ASMDataTable.getAnnotationsFor(ASMDataTable.java:109)
    at cpw.mods.fml.common.network.internal.NetworkModHolder.<init>(NetworkModHolder.java:91)
    at cpw.mods.fml.common.network.NetworkRegistry.register(NetworkRegistry.java:285)
    at cpw.mods.fml.common.FMLContainer.modConstruction(FMLContainer.java:77)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:207)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:186)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:117)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:487)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:194)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:495)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:849)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 8 (amd64) version 6.2
    Java Version: 1.7.0_40, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 370194880 bytes (353 MB) / 611319808 bytes (583 MB) up to 1908932608 bytes (1820 MB)
    JVM Flags: 1 total; -Xmx2048m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.01-pre FML v7.2.106.1012 Minecraft Forge 10.12.0.1012 Optifine OptiFine_1.7.2_HD_U_D1 6 mods loaded, 6 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed
    FML{7.2.106.1012} [Forge Mod Loader](minecraftforge-1.7.2.jar) Unloaded
    Forge{10.12.0.1012} [Minecraft Forge](minecraftforge-1.7.2.jar) Unloaded
    CodeChickenCore{1.0.0} [CodeChicken Core](minecraft.jar) Unloaded
    NotEnoughItems{1.0.1} [Not Enough Items](NotEnoughItems-1.7.2-1.0.1-universal.jar) Unloaded
    inventorytweaks{1.57-116} [Inventory Tweaks](InventoryTweaks-1.57-116.jar) Unloaded
    Launched Version: Forge10.12.0.1012
    LWJGL: 2.9.0
    OpenGL: GeForce GTS 450/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: Español (España)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null
    Anisotropic Filtering: On (16)

**Comment by turocan** [comment]
just say that without inv.tweaks, everything works fine

**Comment by Kobata** [comment]
Did you try with any other normal mod installed? (NEI does things differently) It looks like your version of FML is broken, since it's not even getting to the point of running Inventory Tweaks.

**Comment by turocan** [comment]
so, should look for other NEI version?

**Comment by Kobata** [comment]
Try a mod that isn't NEI or Inventory Tweaks.

**Comment by turocan** [comment]
the same without NEI, will try to change the launcher
