### ISSUE TITLE
Inventory Tweaks 1.58 Crash On Startup Due to Config. File

### ISSUE THREAD

**Issue by Sickliff** [Inventory-Tweaks/inventory-tweaks#170]
I loaded Inventory Tweaks fine before I put my custom configuration file into the .jar. I'll provide both the crash report and the config file.

The crash report:

---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 5/21/14 6:22 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.IllegalAccessError: tried to access field net.minecraft.client.settings.KeyBinding.field_74512_d from class invtweaks.InvTweaksObfuscation
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:688)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:527)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:815)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraft.client.settings.KeyBinding.field_74512_d from class invtweaks.InvTweaksObfuscation
    at invtweaks.InvTweaksObfuscation.getKeyBindingForwardKeyCode(InvTweaksObfuscation.java:102)
    at invtweaks.InvTweaksHandlerShortcuts.loadShortcuts(InvTweaksHandlerShortcuts.java:76)
    at invtweaks.InvTweaksConfigManager.loadConfig(InvTweaksConfigManager.java:144)
    at invtweaks.InvTweaksConfigManager.makeSureConfigurationIsLoaded(InvTweaksConfigManager.java:59)
    at invtweaks.InvTweaks.<init>(InvTweaks.java:105)
    at invtweaks.forge.ClientProxy.init(ClientProxy.java:40)
    at invtweaks.forge.InvTweaksMod.init(InvTweaksMod.java:37)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:687)
    ... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 217191376 bytes (207 MB) / 490209280 bytes (467 MB) up to 954728448 bytes (910 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.03 FML v7.2.196.1084 Minecraft Forge 10.12.1.1084 Optifine OptiFine_1.7.2_HD_U_C2 26 mods loaded, 26 mods active
    mcp{9.03} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FML{7.2.196.1084} [Forge Mod Loader](forge-1.7.2-10.12.1.1084.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Forge{10.12.1.1084} [Minecraft Forge](forge-1.7.2-10.12.1.1084.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CodeChickenCore{1.0.0} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NotEnoughItems{1.0.1} [Not Enough Items](NotEnoughItems-1.7.2-1.0.1-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenEye{0.5} [OpenEye](OpenEye-0.5-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    bspkrsCore{6.8(1.7.2)} [bspkrsCore]([1.7.2]bspkrsCore-universal-6.8%281.7.2%29.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DamageIndicatorsMod{3.0.8} [Damage Indicators]([1.7.2]DamageIndicatorsMod-3.0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DirectionHUD{1.21(1.7.2)} [DirectionHUD]([1.7.2]DirectionHUD-client-1.21%281.7.2%29.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FloatingRuins{1.7.2.r04} [FloatingRuins]([1.7.2]FloatingRuins-universal-1.7.2.r04.jar) Unloaded->Constructed->Pre-initialized->Initialized
    WorldStateCheckpoints{1.7.2.r02} [WorldStateCheckpoints]([1.7.2]WorldStateCheckpoints-client-1.7.2.r02.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AnimationAPI{1.2.1} [AnimationAPI](AnimationAPI-1.7.2-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Backpack{2.0.0-pre1} [Backpack](backpack-2.0.0-pre1-1.7.x.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioCraft{1.7.0} [BiblioCraft](BiblioCraft[1.7.0][MC1.7.2].jar) Unloaded->Constructed->Pre-initialized->Initialized
    Mantle{1.7.2-132.45b0b50} [Mantle](Mantle-1.7.2-0.2.8.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Natura{2.2.0} [Natura](natura-1.7.2-2.2.0a3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiomesOPlenty{2.0.0} [Biomes O' Plenty](BiomesOPlenty-1.7.2-2.0.0.834-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DragonMounts{r38} [Dragon Mounts](dragonmount_r38_mc1.7.x.zip) Unloaded->Constructed->Pre-initialized->Initialized
    HardcoreEnderExpansion{1.6} [Hardcore Ender Expansion](HardcoreEnderExpansion.jar) Unloaded->Constructed->Pre-initialized->Initialized
    inventorytweaks{1.58-dev-123} [Inventory Tweaks](InventoryTweaks-1.58-dev-123.jar) Unloaded->Constructed->Pre-initialized->Errored
    MapWriter{2.1.1} [MapWriter](MapWriter-1.7.2-2.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    meteors{2.12} [Falling Meteors](meteors-1.7.2-2.12.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MutantCreatures{1.4.5} [Mutant Creatures](MutantCreatures-1.7.2-1.4.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Mystcraft{@VERSION@} [Mystcraft](mystcraft-1.7.2-0.10.14.00.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Roguelike{1.3.0} [Roguelike Dungeons](roguelike-1.7.2-1.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TwilightForest{2.0.3} [The Twilight Forest](twilightforest-1.7.2-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized

And the config.:

SpecialSource needs to update to handle these.
public net.minecraft.client.gui.inventory.GuiContainerCreative$ContainerCreative
public net.minecraft.client.gui.inventory.GuiContainerCreative$CreativeSlot
public net.minecraft.client.gui.inventory.GuiContainerCreative$CreativeSlot field_148332_b # theSlot
public net.minecraft.client.settings.KeyBinding field_74512_d # keyCode
public net.minecraft.client.gui.inventory.GuiContainer field_147003_i # guiLeft (1.6 field_74198_m)
public net.minecraft.client.gui.inventory.GuiContainer field_147009_r # guiTop (1.6 field_74197_n)
public net.minecraft.client.gui.inventory.GuiContainer field_146999_f # xSize (1.6 field_74194_b)
public net.minecraft.client.gui.inventory.GuiContainer field_147000_g # ySize (1.6 field_74195_c)
public net.minecraft.client.gui.GuiScreen field_146292_n # buttonList (1.6 field_73887_h)

====== [ SETTINGS ] ======

A3-A8 naturalBlocks
B1-B9 naturalBlocks
A9 edibleFood
B9 edibleFood
C9 edibleFood
A1-A2 Arrows
D1 Sword
D2 Bow
D3 Pickaxe
D4 Shovel
D5 
D6 
D7 
D8 Torch
D9 edibleFood
C1 Sword
C2 Pickaxe
C3 Shovel
C4 Axe

**Comment by Kobata** [comment]
That's more of 'you installed the mod incorrectly' (or some other coremod is decided to overwrite the access changes somehow, probably be being stupid)

**Comment by Sickliff** [comment]
My bad, I was just putting the configuration in the wrong place. Sorry to bother you.
