### ISSUE TITLE
Forge  1095 fresh install and then add Inventory-tweaks

### ISSUE THREAD

**Issue by Narimm** [Inventory-Tweaks/inventory-tweaks#173]
12:39:03] [Sound Library Loader/INFO]: Sound engine started
[12:39:04] [Client thread/INFO]: Created: 1024x512 textures/blocks-atlas
[12:39:04] [Client thread/INFO]: Created: 512x512 textures/items-atlas
[12:39:04] [Client thread/ERROR]: Fatal errors were detected during the transition from INITIALIZATION to POSTINITIALIZATION. Loading cannot continue
[12:39:04] [Client thread/ERROR]: 
    mcp{9.03} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FML{7.2.203.1095} [Forge Mod Loader](forge-1.7.2-10.12.1.1095.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Forge{10.12.1.1095} [Minecraft Forge](forge-1.7.2-10.12.1.1095.jar) Unloaded->Constructed->Pre-initialized->Initialized
    inventorytweaks{1.57-116} [Inventory Tweaks](InventoryTweaks-1.57-116.jar) Unloaded->Constructed->Pre-initialized->Errored
[12:39:04] [Client thread/ERROR]: The following problems were captured during this phase
[12:39:04] [Client thread/ERROR]: Caught exception from inventorytweaks
java.lang.IllegalAccessError: tried to access field net.minecraft.client.settings.KeyBinding.field_74512_d from class invtweaks.InvTweaksObfuscation
    at invtweaks.InvTweaksObfuscation.getKeyBindingForwardKeyCode(InvTweaksObfuscation.java:102) ~[InvTweaksObfuscation.class:?]
    at invtweaks.InvTweaksHandlerShortcuts.loadShortcuts(InvTweaksHandlerShortcuts.java:76) ~[InvTweaksHandlerShortcuts.class:?]
    at invtweaks.InvTweaksConfigManager.loadConfig(InvTweaksConfigManager.java:144) ~[InvTweaksConfigManager.class:?]
    at invtweaks.InvTweaksConfigManager.makeSureConfigurationIsLoaded(InvTweaksConfigManager.java:59) ~[InvTweaksConfigManager.class:?]
    at invtweaks.InvTweaks.<init>(InvTweaks.java:105) ~[InvTweaks.class:?]
    at invtweaks.forge.ClientProxy.init(ClientProxy.java:40) ~[ClientProxy.class:?]
    at invtweaks.forge.InvTweaksMod.init(InvTweaksMod.java:36) ~[InvTweaksMod.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_55]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_55]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_55]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_55]
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513) ~[FMLModContainer.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_55]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_55]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_55]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_55]
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74) ~[guava-15.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47) ~[guava-15.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314) ~[guava-15.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296) ~[guava-15.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:267) ~[guava-15.0.jar:?]
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[LoadController.class:?]
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[LoadController.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_55]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_55]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_55]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_55]
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74) ~[guava-15.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47) ~[guava-15.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314) ~[guava-15.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296) ~[guava-15.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:267) ~[guava-15.0.jar:?]
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:690) [Loader.class:?]
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288) [FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:527) [azd.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:815) [azd.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:103) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_55]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_55]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_55]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_55]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134) [launchwrapper-1.9.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_55]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_55]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_55]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_55]
    at magic.launcher.Launcher.main(SourceFile:207) [MagicLauncher_1.2.5.exe:?]
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Only 1 mod is used to generate the error.
-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.7.0_55, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode, sharing), Oracle Corporation
    Memory: 354251608 bytes (337 MB) / 518979584 bytes (494 MB) up to 518979584 bytes (494 MB)
    JVM Flags: 3 total; -Xms512m -Xmx512m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.03 FML v7.2.203.1095 Minecraft Forge 10.12.1.1095 4 mods loaded, 4 mods active
    mcp{9.03} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FML{7.2.203.1095} [Forge Mod Loader](forge-1.7.2-10.12.1.1095.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Forge{10.12.1.1095} [Minecraft Forge](forge-1.7.2-10.12.1.1095.jar) Unloaded->Constructed->Pre-initialized->Initialized
    inventorytweaks{1.57-116} [Inventory Tweaks](InventoryTweaks-1.57-116.jar) Unloaded->Constructed->Pre-initialized->Errored
# @!@# Game crashed! Crash report saved to: #@!@# C:\Users\benjamincharlton\AppData\Roaming.minecraft\crash-reports\crash-2014-05-26_12.39.04-client.txt

AL lib: (EE) alc_cleanup: 1 device not closed

test edit

**Comment by Narimm** [comment]
Just to clarify I can use this same install and run voxelmap (another mod) ok...

**Comment by Kobata** [comment]
You should post logs if you're reporting things. And say what's actually happening, not just what version of Forge you're using.

**Comment by Narimm** [comment]
1. The logs are in the first post...
2. It shows what version of Minecraft (1.7.2)
3. The log shows exactly whats happening....

mcp{9.03} Minecraft Coder Pack Unloaded->Constructed->Pre-initialized->Initialized
FML{7.2.203.1095} Forge Mod Loader Unloaded->Constructed->Pre-initialized->Initialized
Forge{10.12.1.1095} Minecraft Forge Unloaded->Constructed->Pre-initialized->Initialized
inventorytweaks{1.57-116} Inventory Tweaks Unloaded->Constructed->Pre-initialized->Errored
[12:39:04] [Client thread/ERROR]: The following problems were captured during this phase
[12:39:04] [Client thread/ERROR]: Caught exception from inventorytweaks
java.lang.IllegalAccessError: tried to access field 
net.minecraft.client.settings.KeyBinding.field_74512_d from class invtweaks.InvTweaksObfuscation

As you can see inventory tweaks is trying the keybind but gets IllegalAccessError.

Honestly did you even read the post and not just the title...

**Comment by Kobata** [comment]
The post was empty when I replied, you probably just edited that in.
![post](https://cloud.githubusercontent.com/assets/2323933/3099585/6e590cca-e5ff-11e3-9cc5-6be8b98a4fc2.png)

Anyway, you're installing it incorrectly, magic launcher normally doesn't work right -- it needs to be in the mods folder, nowhere else.

**Comment by Narimm** [comment]
That's weird regarding the post...I definitely posted the logs when I created the issue...mind you I did create the issue and edited them 1 minute after creation.  

I will have a go without using a magiclauncher...to be fair though - I have used magic launcher with 90% of the client mods with no issues...
