### ISSUE TITLE
Invtweaks config Crash on startup

### ISSUE THREAD

**Issue by Arouka** [Inventory-Tweaks/inventory-tweaks#177]
Every time I try to load Inventory Tweaks version 1.57 I get this:

---- Minecraft Crash Report ----
// Sorry :(

Time: 6/8/14 6:37 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.Error: InvTweaks config load failed
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:688)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:527)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:815)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.Error: InvTweaks config load failed
    at invtweaks.InvTweaksConfigManager.loadConfig(InvTweaksConfigManager.java:187)
    at invtweaks.InvTweaksConfigManager.makeSureConfigurationIsLoaded(InvTweaksConfigManager.java:59)
    at invtweaks.InvTweaks.<init>(InvTweaks.java:105)
    at invtweaks.forge.ClientProxy.init(ClientProxy.java:40)
    at invtweaks.forge.InvTweaksMod.init(InvTweaksMod.java:36)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:687)
    ... 10 more
Caused by: java.lang.NullPointerException
    at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:214)
    at invtweaks.InvTweaksItemTree.registerOre(InvTweaksItemTree.java:327)
    at invtweaks.InvTweaksItemTreeLoader.startElement(InvTweaksItemTreeLoader.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
    at javax.xml.parsers.SAXParser.parse(Unknown Source)
    at invtweaks.InvTweaksItemTreeLoader.load(InvTweaksItemTreeLoader.java:51)
    at invtweaks.InvTweaksConfig.load(InvTweaksConfig.java:106)
    at invtweaks.InvTweaksConfigManager.loadConfig(InvTweaksConfigManager.java:175)
    ... 40 more
Caused by: java.lang.NullPointerException
    at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:214)
    at invtweaks.InvTweaksItemTree.registerOre(InvTweaksItemTree.java:327)
    at invtweaks.InvTweaksItemTreeLoader.startElement(InvTweaksItemTreeLoader.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
    at javax.xml.parsers.SAXParser.parse(Unknown Source)
    at invtweaks.InvTweaksItemTreeLoader.load(InvTweaksItemTreeLoader.java:51)
    at invtweaks.InvTweaksConfig.load(InvTweaksConfig.java:106)
    at invtweaks.InvTweaksConfigManager.loadConfig(InvTweaksConfigManager.java:143)
    ... 40 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 281567760 bytes (268 MB) / 728092672 bytes (694 MB) up to 3186360320 bytes (3038 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -Xmx3G -XX:+CMSClassUnloadingEnabled -XX:PermSize=256m -Xincgc
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.03 FML v7.2.194.1079 Minecraft Forge 10.12.1.1079 73 mods loaded, 72 mods active
    mcp{9.03} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FML{7.2.194.1079} [Forge Mod Loader](forge-1.7.2-10.12.1.1079.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Forge{10.12.1.1079} [Minecraft Forge](forge-1.7.2-10.12.1.1079.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AppliedEnergistics2-Core{rv0-beta-19} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CodeChickenCore{1.0.0} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    LittleFix{1.7.2-v1} [LittleFix](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NotEnoughItems{1.0.1} [Not Enough Items](NotEnoughItems-1.7.2-1.0.1-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenEye{0.5} [OpenEye](OpenEye-0.5-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TConstruct-Preloader{0.1.1} [Tinkers Corestruct](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DamageIndicatorsMod{3.1.1} [Damage Indicators]([1.7.2]DamageIndicatorsMod-3.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Core{6.0.15} [BuildCraft](buildcraft-6.0.15.jar) Unloaded->Constructed->Pre-initialized->Initialized
    appliedenergistics2{rv0-beta-19} [Applied Energistics 2](appliedenergistics2-rv0-beta-19.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ArchimedesShips{1.7.2 v1.5.2} [Archimedes' Ships](ArchimedesShips.jar) Unloaded->Constructed->Pre-initialized->Initialized
    asielib{0.2.0} [asielib](AsieLib-1.7.2-0.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BaMsGRAVE{1.4.2_01} [BaM's Grave](bamsgrave-1.7.2-1.4.2_01.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioCraft{1.7.0} [BiblioCraft](BiblioCraft[1.7.0][MC1.7.2].jar) Unloaded->Constructed->Pre-initialized->Initialized
    AWWayofTime{v1.0.1e} [Blood Magic: Alchemical Wizardry](Blood Magic-v1.0.1e.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Botania{beta-37} [Botania](Botania beta-37.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Builders{6.0.15} [BC Builders](buildcraft-6.0.15.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Energy{6.0.15} [BC Energy](buildcraft-6.0.15.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Factory{6.0.15} [BC Factory](buildcraft-6.0.15.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Transport{6.0.15} [BC Transport](buildcraft-6.0.15.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Silicon{6.0.15} [BC Silicon](buildcraft-6.0.15.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CarpentersBlocks{3.1.4} [Carpenter's Blocks](Carpenter's Blocks v3.1.4 - MC 1.7+.zip) Unloaded->Constructed->Pre-initialized->Initialized
    chisel{1.5.3} [Chisel](chisel-1.7.2-1.5.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    craftingpillars{1.5.0} [Crafting Pillars Mod](CraftingPillars-MC1.7.2-1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    denseores{1.0} [denseores](denseores-1.0.jar.zip) Unloaded->Constructed->Pre-initialized->Initialized
    EnderIO{1.1.0_alpha} [Ender IO](enderio-1.1.0_alpha.71.jar) Unloaded->Constructed->Pre-initialized->Initialized
    EnderTanks{rev15} [EnderTanks](EnderTanks-rev15.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ep3{1.7.2-3.0.0b6-dev1} [EnhancedPortals](EnhancedPortals-1.7.2-3.0.0b6-dev1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ForgeMultipart{1.1.0.282} [Forge Multipart](ForgeMultipart-1.7.2-1.1.0.282-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Baubles{1.0.0.14} [Baubles](Baubles-1.7.2-1.0.0.14.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ExtraUtilities{1.1.0-prerelease-6} [Extra Utilities](extrautilities-1.1.0-prerelease-6.jar.zip) Unloaded->Constructed->Pre-initialized->Initialized
    Forestry{2.4.0.0-711} [Forestry for Minecraft](forestry-2.4.0.0-711.jar) Unloaded->Constructed->Pre-initialized->Initialized
    McMultipart{1.1.0.282} [Minecraft Multipart Plugin](ForgeMultipart-1.7.2-1.1.0.282-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    LomLib{2.1.0} [LomLib](LomLib-universal-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    GelsPlus{1.2.0} [Gels+](GelsPlus-universal-1.7.2-1.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    HardcoreEnderExpansion{1.6} [Hardcore Ender Expansion](HardcoreEnderExpansion.jar) Unloaded->Constructed->Pre-initialized->Initialized
    HopperDuctMod{1.3} [Hopper Ducts](hopperductmod-1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    inventorytweaks{1.57-116} [Inventory Tweaks](InventoryTweaks-1.57-116.jar) Unloaded->Constructed->Pre-initialized->Errored
    IronChest{6.0.14.719} [Iron Chest](ironchest-1.7.2-6.0.14.719-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Waila{1.5.2_1.7.2} [Waila](Waila-1.5.2a_1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    JABBA{1.1.3} [Jabba](Jabba_1.1.3_1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Mantle{1.7.2-132.45b0b50} [Mantle](Mantle-1.7.2-0.2.8.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MapWriter{2.1.1} [MapWriter](MapWriter-1.7.2-2.1.1.jar.zip) Unloaded->Constructed->Pre-initialized->Initialized
    TConstruct{1.7.2-1.6.0.jenkins478} [Tinkers' Construct](TConstruct-1.7.2-1.6.0.a14.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Mariculture{b7} [Mariculture](Mariculture-1.7.2-b7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    modularpots{1.7.2.12} [Modular Flower Pots](ModularPots-1.7.2.12.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Morpheus{1.7.2-1.3} [Morpheus](morpheus-1.7.2-1.3.48.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Mystcraft{@VERSION@} [Mystcraft](mystcraft-1.7.2-0.10.14.00.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Natura{2.2.0} [Natura](natura-1.7.2-2.2.0a3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    necromancy{1.6.8} [Necromancy](Necromancy-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ObsidianBoat{v1.3.2} [Obsidian Boat](ObsidianBoat-1.7.2-1.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenComputers|Core{1.0.0} [OpenComputers (Core)](OpenComputers-MC1.7.2-1.2.11.143-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenComputers{1.2.11.143} [OpenComputers](OpenComputers-MC1.7.2-1.2.11.143-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    clayspawn{1.7.2a} [Pam's Clay Spawn](Pam's Clay Spawn 1.7.2a.zip) Unloaded->Constructed->Pre-initialized->Initialized
    desertcraft{1.7.2b} [Pam's DesertCraft](Pam's DesertCraft 1.7.2c.zip) Unloaded->Constructed->Pre-initialized->Initialized
    PneumaticCraft{1.1.14} [PneumaticCraft](PneumaticCraft-1.1.14.jar) Unloaded->Constructed->Pre-initialized->Initialized
    quiverchevsky{b49} [QuiverBow](QuiverBow_1.7.2_b49.zip) Unloaded->Constructed->Pre-initialized->Initialized
    Thaumcraft{4.1.1.14} [Thaumcraft](Thaumcraft-1.7.2-4.1.1.14.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Railcraft{9.0.0.0} [Railcraft](Railcraft_1.7.2-9.0.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    RandomThings{2.0.29} [Random Things](RandomThings-2.0.29.jar) Unloaded->Constructed->Pre-initialized->Initialized
    RefinedRelocation{1.0.4e} [Refined Relocation](RefinedRelocation-1.7.2-1.0.4e.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ti{0.001} [Thaumic Infusion](ThaumicInfusion-0.983.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThaumicTinkerer{alpha-2.3-117} [Thaumic Tinkerer](ThaumicTinkerer-alpha-2.3-117.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TMechworks{1.7.2-60.0ab3ef0} [Tinkers' Mechworks](TMechworks-1.7.2-0.2.7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TwilightForest{2.0.3} [The Twilight Forest](twilightforest-1.7.2-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    weaponmod{1.7.2 v1.14.2} [Balkon's WeaponMod](weaponmod-1.14.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    witchery{0.18.4} [Witchery](witchery-1.7.2-0.18.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ForgeMicroblock{1.1.0.282} [Forge Microblocks](ForgeMultipart-1.7.2-1.1.0.282-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    asielibcore{} [AsieLib CoreMod](minecraft.jar) Unloaded->Disabled
    AE2 Version: beta rv0-beta-19 for Forge 10.12.0.1024
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.

**Comment by Arouka** [comment]
Never mind found the issue it was a crash with crafting pillars fixed in their version 1.5.1
