### ISSUE TITLE
Inventory Tweaks-Thermal Expansion issue

### ISSUE THREAD

**Issue by The-Fireplace** [Inventory-Tweaks/inventory-tweaks#205]
I'm not sure who is at fault here, so I am posting this on both. I run my singleplayer in a separate client and server so I can have Bukkit plugins as well. While I was configuring a Thermal Expansion Hardened Energy Cell, the following error appeared in the console and I was disconnected. The Inventory Tweaks version is 1.58-147-645ca10, and the Thermal Expansion version is 4.0.0B5.

[17:34:44] [Server thread/ERROR]: There was a critical exception handling a packet on channel InventoryTweaks
java.lang.IndexOutOfBoundsException: Index: 44, Size: 36
    at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.7.0_67]
    at java.util.ArrayList.get(Unknown Source) ~[?:1.7.0_67]
    at thermalexpansion.gui.container.ContainerTEBase.func_75144_a(ContainerTEBase.java:147) ~[ContainerTEBase.class:?]
    at invtweaks.network.handlers.ClickMessageHandler.channelRead0(ClickMessageHandler.java:22) ~[ClickMessageHandler.class:?]
    at invtweaks.network.handlers.ClickMessageHandler.channelRead0(ClickMessageHandler.java:12) ~[ClickMessageHandler.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.183]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]

**Comment by Kobata** [comment]
There are a bunch of these crashes with every mod combination nearly possible on OpenEye and a few that are almost entirely vanilla. It's just a random desync between what the server and the client think you have open.
