### ISSUE TITLE
Not compatible with Not Enough Items

### ISSUE THREAD

**Issue by SReject** [Inventory-Tweaks/inventory-tweaks#22]
Using NEI w/ InventoryTweaks crashes the game

To reproduce:
Set gamemode to creative
View survival inventory.

Expected Result:
Being able to view survival inventory with both InventoryTweaks and NEI.

Current Result:
Game Crash

Setup:
Minecraft 1.4.7
Forge: 6.6.2.534
CodeChickenCore: 0.8.1
NEI: 1.4.7.1
InventoryTweaks: 1.0

Minecraft 1.5.1:
Forge: 7.7.0.608
CodeChickenCore: 0.8.5.1
NEI: 1.5.2.6
InventoryTweaks: 1.52

**Comment by Kobata** [comment]
This is an error in NEI, not inventory Tweaks.

And for what it's worth, I have never had it crash and I use both mods and creative a lot in testing -- so there's something strange going on for the people that do.

**Comment by Kobata** [comment]
For more detail (to report for NEI) I dug up one of the old 1.4.7 crash reports:

 java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at codechicken.nei.LayoutManager.onPreDraw(LayoutManager.java:95)
at codechicken.nei.forge.GuiContainerManager.preDraw(GuiContainerManager.java:506)
at avf.a(GuiContainer.java:101)
at avv.a(SourceFile:31)
at avs.a(GuiContainerCreative.java:591)
at ban.b(EntityRenderer.java:1004)
at net.minecraft.client.Minecraft.J(Minecraft.java:882)
at net.minecraft.client.Minecraft.run(Minecraft.java:771)
at java.lang.Thread.run(Unknown Source)

NEI is checking for something with a size >= 1 there, then trying to access the second element of a list.

**Comment by SReject** [comment]
I posted it on the NEI thread aswell. Just trying to spread it to the two mods that conflict in hopes one of the two dev teams find what is going on.
