### ISSUE TITLE
Crashed while picking up items

### ISSUE THREAD

**Issue by HadleyCanine** [Inventory-Tweaks/inventory-tweaks#223]
Been having this crash both in a large (custom) modpack with many other mods installed, and in a mostly-stock Minecraft with only InvTweaks, NEI and MapWriter installed.  While picking up an object, the game will occasionally crash.  Here's the stacktrace:

```
[14:25:27] [Client thread/FATAL]: Unreported exception thrown!

java.lang.IndexOutOfBoundsException: Index: -1, Size: 36
    at java.util.ArrayList$SubList.rangeCheck(Unknown Source) ~[?:1.7.0_72]
    at java.util.ArrayList$SubList.get(Unknown Source) ~[?:1.7.0_72]
    at invtweaks.InvTweaksContainerManager.getSlot(InvTweaksContainerManager.java:344) ~[InvTweaksContainerManager.class:?]
    at invtweaks.InvTweaksContainerManager.move(InvTweaksContainerManager.java:111) ~[InvTweaksContainerManager.class:?]
    at invtweaks.InvTweaksContainerSectionManager.move(InvTweaksContainerSectionManager.java:41) ~[InvTweaksContainerSectionManager.class:?]
    at invtweaks.InvTweaksHandlerAutoRefill$1.run(InvTweaksHandlerAutoRefill.java:195) ~[InvTweaksHandlerAutoRefill$1.class:?]
    at invtweaks.InvTweaks$1.run(InvTweaks.java:122) ~[InvTweaks$1.class:?]
    at invtweaks.InvTweaks.onTick(InvTweaks.java:479) ~[InvTweaks.class:?]
    at invtweaks.InvTweaks.onTickInGame(InvTweaks.java:132) ~[InvTweaks.class:?]
    at invtweaks.forge.ForgeClientTick.onTick(ForgeClientTick.java:24) ~[ForgeClientTick.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_677_ForgeClientTick_onTick_ClientTickEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325) ~[FMLCommonHandler.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1576) ~[bao.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962) ~[bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_72]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_72]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_72]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_72]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
```

Running on Java 1.7.0_72 64-bit under Windows 8.1, Minecraft version 1.7.10, InventoryTweaks 1.59-dev-155.

**Comment by Kobata** [comment]
These happen and I can never figure out where the -1 index is originally coming from. It always seems to happen fairly randomly as well.
