### ISSUE TITLE
Lock up on word load.

### ISSUE THREAD

**Issue by Guyapollo** [Inventory-Tweaks/inventory-tweaks#23]
I've the latest of both inventory-tweaks and Forge. Other mods load fine, but if I have invtweaks set to load, the client freezes up when I try to load a single player world.

2013-03-27 20:07:41 [FINEST] [mcp] Sending event FMLServerAboutToStartEvent to mod mcp
2013-03-27 20:07:41 [FINEST] [mcp] Sent event FMLServerAboutToStartEvent to mod mcp
2013-03-27 20:07:41 [FINEST] [FML] Sending event FMLServerAboutToStartEvent to mod FML
2013-03-27 20:07:41 [FINEST] [FML] Sent event FMLServerAboutToStartEvent to mod FML
2013-03-27 20:07:41 [FINEST] [inventorytweaks] Sending event FMLServerAboutToStartEvent to mod inventorytweaks
2013-03-27 20:07:41 [FINEST] [inventorytweaks] Sent event FMLServerAboutToStartEvent to mod inventorytweaks
2013-03-27 20:07:41 [SEVERE] [ForgeModLoader] Fatal errors were detected during the transition from LOADING to SERVER_ABOUT_TO_START. Loading cannot continue
2013-03-27 20:07:41 [SEVERE] [ForgeModLoader] 
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Available
    FML [Forge Mod Loader](coremods) Unloaded->Available
    inventorytweaks [Inventory Tweaks](InventoryTweaks-1.52.jar) Unloaded->Errored
2013-03-27 20:07:41 [SEVERE] [ForgeModLoader] The following problems were captured during this phase
2013-03-27 20:07:41 [SEVERE] [ForgeModLoader] Caught exception from inventorytweaks
java.lang.NullPointerException
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:512)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:165)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:98)
    at cpw.mods.fml.common.Loader.serverAboutToStart(Loader.java:813)
    at cpw.mods.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:311)
    at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:115)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:355)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
2013-03-27 20:07:41 [SEVERE] [ForgeModLoader] A fatal exception occurred during the server about to start event
java.lang.NullPointerException
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:512)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:165)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:98)
    at cpw.mods.fml.common.Loader.serverAboutToStart(Loader.java:813)
    at cpw.mods.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:311)
    at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:115)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:355)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
2013-03-27 20:07:41 [INFO] [Minecraft-Server] Stopping server
2013-03-27 20:07:41 [INFO] [Minecraft-Server] Saving players
2013-03-27 20:07:41 [INFO] [Minecraft-Server] Saving worlds
2013-03-27 20:07:41 [INFO] [STDERR] java.lang.NullPointerException
2013-03-27 20:07:41 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:271)
2013-03-27 20:07:41 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:316)
2013-03-27 20:07:41 [INFO] [STDERR]     at net.minecraft.server.integrated.IntegratedServer.func_71260_j(IntegratedServer.java:224)
2013-03-27 20:07:41 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:447)
2013-03-27 20:07:41 [INFO] [STDERR]     at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
2013-03-27 20:07:41 [FINEST] [mcp] Sending event FMLServerStoppedEvent to mod mcp
2013-03-27 20:07:41 [FINEST] [mcp] Sent event FMLServerStoppedEvent to mod mcp
2013-03-27 20:07:41 [FINEST] [FML] Sending event FMLServerStoppedEvent to mod FML
2013-03-27 20:07:41 [FINEST] [FML] Sent event FMLServerStoppedEvent to mod FML
2013-03-27 20:07:41 [FINEST] [inventorytweaks] Sending event FMLServerStoppedEvent to mod inventorytweaks
2013-03-27 20:07:41 [FINEST] [inventorytweaks] Sent event FMLServerStoppedEvent to mod inventorytweaks
2013-03-27 20:07:41 [SEVERE] [ForgeModLoader] Fatal errors were detected during the transition from ERRORED to SERVER_STOPPED. Loading cannot continue
2013-03-27 20:07:41 [SEVERE] [ForgeModLoader] 
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Available->Available
    FML [Forge Mod Loader](coremods) Unloaded->Available->Available
    inventorytweaks [Inventory Tweaks](InventoryTweaks-1.52.jar) Unloaded->Errored->Errored
2013-03-27 20:07:41 [SEVERE] [ForgeModLoader] The following problems were captured during this phase
2013-03-27 20:07:41 [SEVERE] [ForgeModLoader] Caught exception from inventorytweaks
java.lang.NullPointerException
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:512)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:165)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:98)
    at cpw.mods.fml.common.Loader.serverAboutToStart(Loader.java:813)
    at cpw.mods.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:311)
    at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:115)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:355)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
2013-03-27 20:07:41 [SEVERE] [ForgeModLoader] Caught exception from inventorytweaks
java.lang.NullPointerException
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:512)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:165)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:98)
    at cpw.mods.fml.common.Loader.serverStopped(Loader.java:796)
    at cpw.mods.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:470)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:456)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
2013-03-27 20:07:41 [INFO] [STDERR] Exception in thread "Server thread" java.lang.NullPointerException
2013-03-27 20:07:41 [INFO] [STDERR]     at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:512)
2013-03-27 20:07:41 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-03-27 20:07:41 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2013-03-27 20:07:41 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-03-27 20:07:41 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Unknown Source)
2013-03-27 20:07:41 [INFO] [STDERR]     at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
2013-03-27 20:07:41 [INFO] [STDERR]     at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
2013-03-27 20:07:41 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
2013-03-27 20:07:41 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
2013-03-27 20:07:41 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.post(EventBus.java:267)
2013-03-27 20:07:41 [INFO] [STDERR]     at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:165)
2013-03-27 20:07:41 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-03-27 20:07:41 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2013-03-27 20:07:41 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-03-27 20:07:41 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Unknown Source)
2013-03-27 20:07:41 [INFO] [STDERR]     at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
2013-03-27 20:07:41 [INFO] [STDERR]     at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
2013-03-27 20:07:41 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
2013-03-27 20:07:41 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
2013-03-27 20:07:41 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.post(EventBus.java:267)
2013-03-27 20:07:41 [INFO] [STDERR]     at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:98)
2013-03-27 20:07:41 [INFO] [STDERR]     at cpw.mods.fml.common.Loader.serverAboutToStart(Loader.java:813)
2013-03-27 20:07:41 [INFO] [STDERR]     at cpw.mods.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:311)
2013-03-27 20:07:41 [INFO] [STDERR]     at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:115)
2013-03-27 20:07:41 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:355)
2013-03-27 20:07:41 [INFO] [STDERR]     at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)

**Comment by Kobata** [comment]
Install Forge (http://files.minecraftforge.net/minecraftforge/minecraftforge-universal-recommended.zip), not the FML stand-alone package.

**Comment by Guyapollo** [comment]
For the record I've used Modloader untill about 4 hours ago =3
