### ISSUE TITLE
Auto-refill and Dual Hotbar crash

### ISSUE THREAD

**Issue by AltonV** [Inventory-Tweaks/inventory-tweaks#275]
When inventory tweaks tries to auto-refill to the extra slots from dual hotbars it crashes the game.

java.lang.IndexOutOfBoundsException: Index: 41, Size: 36
    at java.util.ArrayList$SubList.rangeCheck(ArrayList.java:1217)
    at java.util.ArrayList$SubList.get(ArrayList.java:1034)
    at invtweaks.InvTweaksContainerManager.indexToSlot(InvTweaksContainerManager.java:446)
    at invtweaks.InvTweaksContainerManager.getItemStack(InvTweaksContainerManager.java:409)
    at invtweaks.InvTweaksContainerManager.move(InvTweaksContainerManager.java:99)
    at invtweaks.InvTweaksContainerSectionManager.move(InvTweaksContainerSectionManager.java:41)
    at invtweaks.InvTweaksHandlerAutoRefill$1.run(InvTweaksHandlerAutoRefill.java:195)
    at invtweaks.InvTweaks$1.run(InvTweaks.java:122)
    at invtweaks.InvTweaks.onTick(InvTweaks.java:479)
    at invtweaks.InvTweaks.onTickInGame(InvTweaks.java:132)
    at invtweaks.forge.ForgeClientTick.onTick(ForgeClientTick.java:24)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_638_ForgeClientTick_onTick_ClientTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1587)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Kobata** [comment]
#263

Use search including closed issues.
