### ISSUE TITLE
Inventory Tweaks and Optifine Incompatible? 

### ISSUE THREAD

**Issue by AlexTu2** [Inventory-Tweaks/inventory-tweaks#281]
I get this error when i have Inventory Tweaks and Optifine in mods 

Caused by: java.lang.IncompatibleClassChangeError: Implementing class
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_25]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_25]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_25]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_25]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    at net.minecraft.block.state.BlockState.createState(BlockState.java:55) ~[bed.class:?]
    at net.minecraft.block.state.BlockState.<init>(BlockState.java:83) ~[bed.class:?]
    at net.minecraft.block.state.BlockState.<init>(BlockState.java:50) ~[bed.class:?]
    at net.minecraft.block.Block.func_180661_e(Block.java:968) ~[atr.class:?]
    at net.minecraft.block.Block.<init>(Block.java:248) ~[atr.class:?]
    at net.minecraft.block.BlockAir.<init>(BlockAir.java:15) ~[asy.class:?]
    at net.minecraft.block.Block.func_149671_p(Block.java:2021) ~[atr.class:?]
    at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:554) ~[od.class:?]
    at net.minecraft.client.Minecraft.<init>(Minecraft.java:315) ~[bsu.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:120) ~[Main.class:?]
    ... 6 more
Exception in thread "Client thread" [10:49:41] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[10:49:41] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[10:49:41] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[10:49:41] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.Runtime.exit(Runtime.java:107)
[10:49:41] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.System.exit(System.java:968)
[10:49:41] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[10:49:41] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Kobata** [comment]
I don't think this is anything to do with inventory tweaks, but it could be a Forge/OF incompatibility.
