### ISSUE TITLE
Crash Error Upon Loading Up Forge

### ISSUE THREAD

**Issue by Hyuukichan123** [Inventory-Tweaks/inventory-tweaks#284]
I seem to be having a issue where inventory tweaks crashes the forge loader upon half way through the installation. I am using the 1.7.10 version and at first I thought it was thaumcraft causing my game to crash. But upon process of elimination i found that the Inventory tweaks mod was the reason for my game crashing. Is there a problem with the 1.7.10 version? I tried previous updates of it including the 1.5.7 before the 1.5.8 update. I cannot use the 1.8 version of IT right now due to the fact that the other mods im using still havent updated to 1.8. I've tried multiple downloads to fix the issue but each of the files seems to have the same crashing issue. Is there another mod I'm supposed to download with IT along side? Like an API or GUI?

**Comment by Hyuukichan123** [comment]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 9/4/15 2:23 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.IllegalAccessError: tried to access field net.minecraft.client.settings.KeyBinding.field_74512_d from class invtweaks.InvTweaksObfuscation
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraft.client.settings.KeyBinding.field_74512_d from class invtweaks.InvTweaksObfuscation
    at invtweaks.InvTweaksObfuscation.getKeyBindingForwardKeyCode(InvTweaksObfuscation.java:102)
    at invtweaks.InvTweaksHandlerShortcuts.loadShortcuts(InvTweaksHandlerShortcuts.java:76)
    at invtweaks.InvTweaksConfigManager.loadConfig(InvTweaksConfigManager.java:144)
    at invtweaks.InvTweaksConfigManager.makeSureConfigurationIsLoaded(InvTweaksConfigManager.java:59)
    at invtweaks.InvTweaks.<init>(InvTweaks.java:108)
    at invtweaks.forge.ClientProxy.init(ClientProxy.java:51)
    at invtweaks.forge.InvTweaksMod.init(InvTweaksMod.java:40)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
    ... 10 more

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Mac OS X (x86_64) version 10.6.8
    Java Version: 1.6.0_65, Apple Inc.
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
    Memory: 172344032 bytes (164 MB) / 373907456 bytes (356 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 17 mods loaded, 17 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHI    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHI    FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1448-1.7.10.jar) 
    UCHI    Forge{10.13.4.1448} [Minecraft Forge](forge-1.7.10-10.13.4.1448-1.7.10.jar) 
    UCHI    Backpack{2.0.1} [Backpack](backpack-2.0.1-1.7.x) 
    UCHI    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10) 
    UCHI    BiblioCraft{1.10.5} [BiblioCraft](BiblioCraft[v1.10.6][MC1.7.10]) 
    UCHI    craftguide{1.6.8.1} [CraftGuide](CraftGuide-Mod-1.7.10) 
    UCHI    DamageIndicatorsMod{3.2.0} [Damage Indicators](Damage-Indicators-Mod-1.7.10) 
    UCHI    eplus{3.0.2-d} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.2-d) 
    UCHI    ExtraUtilities{1.2.11} [Extra Utilities](extrautilities-1.2.11) 
    UCHI    harvestcraft{1.7.10d} [Pam's HarvestCraft](HarvestCraft-Mod-1.7.10) 
    UCHE    inventorytweaks{1.58-147-645ca10} [Inventory Tweaks](InventoryTweaks-1.58-147 2) 
    UCHI    IronChest{6.0.41.729} [Iron Chest](Iron-Chests-Mod-1.7.10) 
    UCHI    Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2) 
    UCHI    MoreFurnaces{1.3.9} [More Furnaces](More-Furnaces-Mod-1.7.10) 
    UCHI    sus{4.0.10} [Superheroes Unlimited Mod](Superheroes Unlimited Mod-1.7.10-4.0.10 2) 
    UCHI    TConstruct{1.7.10-1.8.7.build979} [Tinkers' Construct](TConstruct-1.7.10-1.8.7) 
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '2.0 ATI-1.6.36' Renderer: 'ATI Radeon X1600 OpenGL Engine'
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.

This is the crash report if it helps any....

**Comment by Kobata** [comment]
That's generally indicative of an install problem (particularly some annoying launchers that try to overlay things into the main jar instead of installing mods properly), or a conflict with another mod.
