### ISSUE TITLE
Hasn't Worked For Me Since Inventory Tweaks v1.51

### ISSUE THREAD

**Issue by meiamone** [Inventory-Tweaks/inventory-tweaks#29]
Launcher MultiMC, MC version 1.5.1, mods loading: Rei's Minimap, Forge 7.7.0.600, Optifine 1.5.1 HD_U_B1, TooManyItems2013_03_23_1.5.1.
Error from launcher console:
"C:\Program Files\Java\jre7\bin\java.exe"  -Xms512m -Xmx1024m -jar MultiMCLauncher.jar  "meiamone" "-1713655144473578438" "MultiMC: Pearl" "1280x720" "Mojang"

Loading jars...
Loading URL: file:/C:/Users/Administrator/Documents/Minecraft/Apps/MultiMC/instances/Pearl/minecraft/bin/minecraft.jar
Loading URL: file:/C:/Users/Administrator/Documents/Minecraft/Apps/MultiMC/instances/Pearl/minecraft/bin/lwjgl.jar
Loading URL: file:/C:/Users/Administrator/Documents/Minecraft/Apps/MultiMC/instances/Pearl/minecraft/bin/lwjgl_util.jar
Loading URL: file:/C:/Users/Administrator/Documents/Minecraft/Apps/MultiMC/instances/Pearl/minecraft/bin/jinput.jar
Loading natives...
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
    at sun.security.util.SignatureFileVerifier.processImpl(Unknown Source)
    at sun.security.util.SignatureFileVerifier.process(Unknown Source)
    at java.util.jar.JarVerifier.processEntry(Unknown Source)
    at java.util.jar.JarVerifier.update(Unknown Source)
    at java.util.jar.JarFile.initializeVerifier(Unknown Source)
    at java.util.jar.JarFile.getInputStream(Unknown Source)
    at sun.misc.URLClassPath$JarLoader$2.getInputStream(Unknown Source)
    at sun.misc.Resource.cachedInputStream(Unknown Source)
    at sun.misc.Resource.getByteBuffer(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$100(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at MultiMCLauncher.main(MultiMCLauncher.java:157)
Minecraft exited with code 4.
Minecraft has crashed!

**Comment by Kobata** [comment]
This is an issue with either your minecraft jar file or forge version being invalid, or the method of installation for jar mods, nothing to do with Inventory Tweaks.

Make sure the order of installation is forge then optifine, and that you are using an unmodified 1.5.1 jar file as the base. I would recommend using Not Enough Items over Too Many Items in most cases (despite a small set of people having issues with creative mode), as it does not need to be installed in the jar and is more directly compatible with forge.
