### ISSUE TITLE
1.9 Crash

### ISSUE THREAD

**Issue by TrikSteve** [Inventory-Tweaks/inventory-tweaks#346]
**Minecraft Version: 1.9**
**Inventory Tweaks Version: 1.6.1 dev 45**
Forge: 1863

Crashes on startup with other mod conflicts.  Main one was Tech Reborn.  Also Silent's Gems and TSON Craft.
Pastebin: http://pastebin.com/raw/hJBGEDbw

**Comment by ghost** [comment]
Not gonna open other Issue as my problem is the same. It does work on 1.9 but as soon as you combine with some other specific mods it crashes. In this case TSon Craft also, as TrikSteve mentions.

Not sure "whose fault" this is, but gonna drop the crash log here also.

http://pastebin.com/f7wJy3fY

Thanks a lot...

**Comment by Zkaface** [comment]
Yep, InvTweaks need to be updated to new Forge Version.

**Comment by siverson101** [comment]
My crash happens when combined with plantmegapack-1.9.5.jar.

http://paste.ee/p/cCkj7

Caused by: java.lang.IllegalAccessError: tried to access field net.minecraftforge.oredict.OreDictionary$OreRegisterEvent.Name from class invtweaks.InvTweaksItemTree
at invtweaks.InvTweaksItemTree.lambda$oreRegistered$5(InvTweaksItemTree.java:288)
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
...
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
at invtweaks.InvTweaksItemTree.oreRegistered(InvTweaksItemTree.java:288)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_25_InvTweaksItemTree_oreRegistered_OreRegisterEvent.invoke(.dynamic)
...
at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:467)
at plantmegapack.item.PMPItemBook.<init>(PMPItemBook.java:38)
at plantmegapack.core.PMPItems.initClient(PMPItems.java:89)
at plantmegapack.core.PMPProxyClient.init(PMPProxyClient.java:24)
at plantmegapack.PlantMegaPack.init(PlantMegaPack.java:67) 

It worked fine with:
BetterAchievements-1.9-0.2.2.jar
decorationmegapack-1.9.1.jar
Doomlike-Dungeons-Mod-1.9.jar
hopperducts-mc1.9-1.4.7.jar
LemonsSimpleTeleporters-1.1.1.jar
LunatriusCore-1.9-1.1.2.33-universal.jar

**Comment by Kobata** [comment]
#342
