### ISSUE TITLE
1.9 Crash with tech reborn

### ISSUE THREAD

**Issue by skye-repos** [Inventory-Tweaks/inventory-tweaks#357]
**Minecraft Version:** 1.9
**Inventory Tweaks Version:** 1.6.1 dev 49

The game insta crashes when loading with tech reborn.
It doesn't even get past initialisation. Crashes w/ Inv tweaks and doesn't w/o.
Doesn't crash w/o inv tweaks and w/ tech reborn.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-beta-18.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.9-2.0.1.53-universal.jar)
  NowWithRendering (redstonepaste-mc1.9-1.7.3.jar)
  CCLCorePlugin (CodeChickenLib-1.9-2.0.1.6-universal.jar)
  FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  LoadingPlugin (RandomThings-MC1.9-3.7.jar)
  Reborn Core ASM (RebornCore-1.9-2.1.0.53-universal.jar)
  RegionalWaterCore (RegionalWater-1.9.0-1.0.1.jar)
  CCCDeobfPlugin (unknown)
  FMLPlugin (InventoryTweaks-1.61-dev-49 (1).jar)
  LoadingPlugin (ResourceLoader-MC1.9-1.5.jar)
  CCLCorePlugin (CodeChickenLib-1.9-2.0.1.23-universal.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 14/5/16 8:49 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.IllegalAccessError: tried to access field net.minecraftforge.oredict.OreDictionary$OreRegisterEvent.Name from class invtweaks.InvTweaksItemTree
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:179)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:767)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:316)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraftforge.oredict.OreDictionary$OreRegisterEvent.Name from class invtweaks.InvTweaksItemTree
    at invtweaks.InvTweaksItemTree.lambda$oreRegistered$5(InvTweaksItemTree.java:288)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at invtweaks.InvTweaksItemTree.oreRegistered(InvTweaksItemTree.java:288)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_403_InvTweaksItemTree_oreRegistered_OreRegisterEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:613)
    at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:560)
    at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:558)
    at cyano.steamadvantage.init.Recipes.init(Recipes.java:26)
    at cyano.steamadvantage.SteamAdvantage.init(SteamAdvantage.java:122)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:561)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:765)
    ... 18 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.9
    Operating System: Mac OS X (x86_64) version 10.11.3
    Java Version: 1.8.0_73, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 900972816 bytes (859 MB) / 2090860544 bytes (1994 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 2 total; -Xms512m -Xmx4096m
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.23 Powered by Forge 12.16.1.1904 88 mods loaded, 88 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHI    mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHI    FML{8.0.99.99} [Forge Mod Loader](forge-1.9-12.16.1.1904-universal.jar) 
    UCHI    Forge{12.16.1.1904} [Minecraft Forge](forge-1.9-12.16.1.1904-universal.jar) 
    UCHI    CodeChickenCore{2.0.1.53} [CodeChicken Core](minecraft.jar) 
    UCHI    regionalwater{1.7.10-1.0} [Regional Water](minecraft.jar) 
    UCHI    autopackager{1.6.1} [AutoPackager](autopackager-1.6.1.jar) 
    UCHI    bagginses{2.3.0b} [Bagginses](Bagginses-1.9-2.3.0b.jar) 
    UCHI    basemetals{2.2.2} [Base Metals](BaseMetals_1.9-2.2.2.jar) 
    UCHI    Baubles{1.2.0.2} [Baubles](Baubles-1.9-1.2.0.2.jar) 
    UCHI    baublesstuff{2.0.8} [Baubles Stuff](baublesstuff-2.0.8.jar) 
    UCHI    bdlib{1.11.0.14} [BD Lib](bdlib-1.11.0.14-mc1.9.jar) 
    UCHI    betterbuilderswands{0.6.0} [Better Builder's Wands](BetterBuildersWands-0.6.0-1.9r124+c748dee.jar) 
    UCHI    JEI{3.3.3.200} [Just Enough Items](jei_1.9-3.3.3.200.jar) 
    UCHI    BloodMagic{1.9-2.0.0-37} [Blood Magic: Alchemical Wizardry](BloodMagic-1.9-2.0.0-37.jar) 
    UCHI    bookshelf{1.2.0.237} [Bookshelf](Bookshelf-1.9-1.2.0.242.jar) 
    UCHI    Botania{r1.8-304} [Botania](Botania-unofficial.r1.8-304.jar) 
    UCHI    Chameleon{1.9-2.1.3} [Chameleon](Chameleon-1.9-2.1.3.jar) 
    UCHI    ChickenChunks{2.0.1.26} [ChickenChunks](ChickenChunks-1.9-2.0.1.26-universal.jar) 
    UCHI    chisel{@VERSION@} [Chisel](Chisel-MC1.9-0.0.4.14.jar) 
    UCHI    mcmultipart{1.1.1} [MCMultiPart](MCMultiPart-1.1.1-universal.jar) 
    UCHI    chiselsandbits{9.18} [Chisels & Bits](chiselsandbits-9.18.jar) 
    UCHI    cookingforblockheads{2.0.10} [Cooking for Blockheads](CookingForBlockheads-mc1.9-2.0.10.jar) 
    UCHI    CustomMainMenu{2.0} [Custom Main Menu](CustomMainMenu-MC1.9-2.0.jar) 
    UCHI    ElecCore{1.4.270} [ElecCore](ElecCore-1.9-1.4.270.jar) 
    UCHI    deepresonance{1.1.4beta30} [DeepResonance](deepresonance-1.9.0-1.1.4beta30.jar) 
    UCHI    eggs{1.0} [Eat the Eggs!](Eat the Eggs-1.9-0.9 beta.jar) 
    UCHI    poweradvantage{2.1.1} [Power Advantage](PowerAdvantage_1.9.0-2.1.1.jar) 
    UCHI    electricadvantage{2.0.3} [Electric Advantage](ElectricAdvantage_1.9-2.0.3.jar) 
    UCHI    eplus{4.1.0.86} [Enchanting Plus](EnchantingPlus-1.9-4.1.0.97.jar) 
    UCHI    EnderBags{1.0.2} [EnderBags](EnderBags-1.9-1.0.2.jar) 
    UCHI    endercrop{1.9-1.2-1836} [Ender Crop](endercrop-1.9.1.3.jar) 
    UCHI    enderthing{0.6.6} [Enderthing](enderthing-1.9-0.6.6.jar) 
    UCHI    excore{1.5.3} [EXCore](Excore-1.5.3-1.9.jar) 
    UCHI    ezstorage{1.0} [EZ Storage](ezstorage-1.9-1.2.1.jar) 
    UCHI    fastleafdecay{1.6} [Fast Leaf Decay](FastLeafDecay-1.9-1.6.jar) 
    UCHI    fluxducts{1.0.3} [Flux Ducts](fluxducts-mc1.9-1.0.3.jar) 
    UCHI    fe{1.2} [Food Expansion](FoodExpansion1.2-mc1.9.jar) 
    UCHI    moreoverlays{1.3.1} [MoreOverlays](moreoverlays-1.3.1-mc1.9.jar) 
    UCHI    FEI{1.0.8} [Forever Enough Items](ForeverEnoughItems-1.0.8-1.9.jar) 
    UCHI    pressure{1.3.1.13} [Pressure Pipes](pressure-1.3.1.13-mc1.9.jar) 
    UCHI    advgenerators{0.9.20.9} [Advanced Generators](generators-0.9.20.9-mc1.9.jar) 
    UCHI    grapple_hooks{1.0.8} [Grapple Hooks](Grapple Hooks-1.9-1.0.8.jar) 
    UCHI    gravestone{1.2.4} [Gravestone](Gravestone Mod 1.2.4 .jar) 
    UCHI    Harvest{1.9-1.0.1-3} [Harvest](Harvest-1.9-1.0.1-3.jar) 
    UCHI    HardcoreQuesting{5.0.0alpha1} [Hardcore Questing Mode](HQM-New Heights-5.0.0alpha1.jar) 
    UCHI    inventorytweaks{1.61-dev-49-c5b6395} [Inventory Tweaks](InventoryTweaks-1.61-dev-49 %281%29.jar) 
    UCHI    IronChest{6.0.133.777} [Iron Chest](ironchest-1.9-6.0.133.777.jar) 
    UCHI    itemscroller{0.4.2} [Item Scroller](itemscroller-1.9-0.4.2.jar) 
    UCHI    japta{1.5.1} [JAPTA](JAPTA-1.9-1.5.1.jar) 
    UCHI    journeymap{1.9-5.2.0b1} [JourneyMap](journeymap-1.9-5.2.0b1-unlimited.jar) 
    UCHI    jeresources{0.4.5.27} [Just Enough Resources](JustEnoughResources-1.9-0.4.5.27.jar) 
    UCHI    Login_Shield_MC1.9{1.2-21-g08fa29a} [Login Shield](Login_Shield_MC1.9-1.2-21-g08fa29a.jar) 
    UCHI    mantle{1.9-0.10.0.jenkins132} [Mantle](Mantle-1.9-0.10.0.jar) 
    UCHI    Morpheus{1.9-3.0.2} [Morpheus](Morpheus-1.9-3.0.2.jar) 
    UCHI    netherportalfix{1.0} [Nether Portal Fix](netherportalfix-mc1.9-3.0.6.jar) 
    UCHI    nmsot{1.1.3-mc1.9} [No Mob Spawning on Trees](NoMobSpawningOnTrees-1.1.3-mc1.9.jar) 
    UCHI    notenoughwands{1.3.3} [Not Enough Wands](notenoughwands-1.9.0-1.3.3.jar) 
    UCHI    fodc{1.8.1} [Ore Dictionary Converter](OreDictionaryConverter-1.8.1.jar) 
    UCHI    packingtape{0.5.1} [Packing Tape](Packing Tape-0.5.1.jar) 
    UCHI    progressiveautomation{1.6.42} [Progressive Automation](ProgressiveAutomation-1.9-1.6.42.jar) 
    UCHI    Psi{beta-31} [Psi](Psi-beta-31.jar) 
    UCHI    quantumflux{2.0.6} [QuantumFlux](quantumflux-1.9-2.0.6.jar) 
    UCHI    Quark{beta-18} [Quark](Quark-beta-18.jar) 
    UCHI    randomthings{3.7} [Random Things](RandomThings-MC1.9-3.7.jar) 
    UCHI    reborncore{2.1.0.53} [RebornCore](RebornCore-1.9-2.1.0.53-universal.jar) 
    UCHI    redstonepaste{1.7.3} [Redstone Paste](redstonepaste-mc1.9-1.7.3.jar) 
    UCHI    ResourceLoader{1.5} [Resource Loader](ResourceLoader-MC1.9-1.5.jar) 
    UCHI    rftools{4.47} [RFTools](rftools-1.9.0-4.47.jar) 
    UCHI    rftoolsdim{4.23beta38} [RFTools Dimensions](rftoolsdim-1.9.0-4.23beta38.jar) 
    UCHI    Roguelike{1.5.0} [Roguelike Dungeons](RoguelikeDungeons-1.9-1.5.0.jar) 
    UCHI    routerreborn{1.9-4.0.1.11b_universal} [Router Reborn](RouterReborn-1.9-4.0.1.11b_universal.jar) 
    UCHE    SaltMod{1.8.c} [Salty Mod](SaltyMod-1.9-1.8.c_beta-1.jar) 
    UCHI    shadowmc{3.1.0} [ShadowMC](ShadowMC-1.9-3.1.4.jar) 
    UCHI    SimpleLabels{0.0.1} [SimpleLabels](simplelabels-0.0.2.jar) 
    UCHI    simpleretrogen{2.2.3+4} [Simple Retrogen](simpleretrogen-1.9-2.2.3+4.jar) 
    UCHI    SleepingBag{1.1.0} [Sleeping Bag](SleepingBag-1.9-1.1.0.jar) 
    UCHI    soulshardstow{1.9-2.3.9-25} [Soul Shards - The Old Ways](SoulShards-TOW-1.9-2.3.9-25.jar) 
    UCHE    steamadvantage{2.0.3} [Steam Advantage](SteamAdvantage_1.9-2.0.3.jar) 
    UCHI    StorageDrawers{1.9-3.1.6} [Storage Drawers](StorageDrawers-1.9-3.1.6.jar) 
    UCHI    tconstruct{1.9-2.3.0.jenkins193} [Tinkers' Construct](TConstruct-1.9-2.3.0.jar) 
    UCHE    techreborn{1.0.6.197} [TechReborn](TechReborn-1.9-1.0.6.197-universal.jar) 
    UCHI    Trashcans{2.0.2} [Trashcans](Trashcans-1.9-2.0.2.jar) 
    UCHI    Waila{1.7.0} [Waila](Waila-1.7.0-B2_1.9.jar) 
    UCHI    wailafeatures{@MAJOR@.@MINOR@.@REVIS@} [WAILA Features](WAILA-features-1.9-0.3.1.6.jar) 
    UCHI    WailaHarvestability{1.1.7} [Waila Harvestability](WailaHarvestability-mc1.9-1.1.7.jar) 
    UCHI    ICSE{1.0.0.0} [I Can See Everything](Wawla-1.9-2.2.0.186.jar) 
    UCHI    wawla{2.2.0.178} [What Are We Looking At](Wawla-1.9-2.2.0.186.jar) 
    UCHI    Woot{1.9-0.6.1-beta} [Woot](woot-1.9-0.6.1-beta.jar) 
    Loaded coremods (and transformers): 
LoadingPlugin (Quark-beta-18.jar)
  vazkii.quark.base.asm.ClassTransformer
CodeChickenCorePlugin (CodeChickenCore-1.9-2.0.1.53-universal.jar)
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
NowWithRendering (redstonepaste-mc1.9-1.7.3.jar)
  net.fybertech.nwr.NowWithRendering
CCLCorePlugin (CodeChickenLib-1.9-2.0.1.6-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
LoadingPlugin (RandomThings-MC1.9-3.7.jar)
  lumien.randomthings.asm.ClassTransformer
Reborn Core ASM (RebornCore-1.9-2.1.0.53-universal.jar)
  reborncore.asm.RebornClassTransformer
RegionalWaterCore (RegionalWater-1.9.0-1.0.1.jar)
  com.velleth.regionalwater.RWClassTransformer
CCCDeobfPlugin (unknown)

FMLPlugin (InventoryTweaks-1.61-dev-49 (1).jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (ResourceLoader-MC1.9-1.5.jar)
  lumien.resourceloader.asm.ClassTransformer
CCLCorePlugin (CodeChickenLib-1.9-2.0.1.23-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1 NVIDIA-10.8.14 310.42.15f01' Renderer: 'NVIDIA GeForce GT 650M OpenGL Engine'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)

```
List of loaded APIs: 
    * Baubles|API (1.1.1.0) from Baubles-1.9-1.2.0.2.jar
    * BloodMagic|API (@VERSION@) from BloodMagic-1.9-2.0.0-37.jar
    * BotaniaAPI (78) from Botania-unofficial.r1.8-304.jar
    * ChiselAPI (0.0.1) from Chisel-MC1.9-0.0.4.14.jar
    * ChiselAPI|Carving (0.0.1) from Chisel-MC1.9-0.0.4.14.jar
    * ChiselsAndBitsAPI (1.8.1) from chiselsandbits-9.18.jar
    * CoFHAPI (1.8.9R1.2.0B1) from RebornCore-1.9-2.1.0.53-universal.jar
    * CoFHAPI|block (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9-1.6.42.jar
    * CoFHAPI|energy (1.8.9R1.2.0B1) from mcjtylib-1.9.0-1.8.4.jar
    * CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9-1.6.42.jar
    * DR-API (1.0.4-Beta) from deepresonance-1.9.0-1.1.4beta30.jar
    * ElecCore|Abilities (#API_VER#) from ElecCore-1.9-1.4.270.jar
    * IC2API (1.0) from RebornCore-1.9-2.1.0.53-universal.jar
    * jeresources|API (0.4.5.27) from JustEnoughResources-1.9-0.4.5.27.jar
    * journeymap|client-api (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
    * journeymap|client-api-display (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
    * journeymap|client-api-event (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
    * journeymap|client-api-model (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
    * journeymap|client-api-util (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
    * JustEnoughItemsAPI (3.1.0) from jei_1.9-3.3.3.200.jar
    * McJtyLib (1.9.0-1.8.4) from mcjtylib-1.9.0-1.8.4.jar
    * pressureAPI (1.3.1.13) from pressure-1.3.1.13-mc1.9.jar
    * PsiAPI (2) from Psi-beta-31.jar
    * reborncoreAPI (2.1.0.53) from RebornCore-1.9-2.1.0.53-universal.jar
    * SoulShardsTOW|API (0.1.5) from SoulShards-TOW-1.9-2.3.9-25.jar
    * StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
    * StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
    * StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
    * StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
    * StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
    * StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
    * StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
    * StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
    * StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
    * techrebornAPI (1.0.6.197) from TechReborn-1.9-1.0.6.197-universal.jar
    * WailaAPI (1.3) from Waila-1.7.0-B2_1.9.jar
```

**Comment by skye-repos** [comment]
I understand that this has been marked as duplicate. Could you elaborate further? Which one is this a dupe of? I cant find it. When will it be fixed? will it be fixed?
