### ISSUE TITLE
Client Crash: NoSuchMethodError

### ISSUE THREAD

**Issue by Isep321** [Inventory-Tweaks/inventory-tweaks#372]
**Minecraft Version:**
1.10.2
**Inventory Tweaks Version:**
1.61-58

java.lang.NoSuchMethodError: invtweaks.api.IItemTreeItem.getExtraData()Lnet/minecraft/nbt/NBTTagCompound;
    at invtweaks.InvTweaksItemTree.lambda$getItems$5(InvTweaksItemTree.java:191)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at invtweaks.InvTweaksItemTree.getItems(InvTweaksItemTree.java:191)
    at invtweaks.InvTweaksHandlerSorting.getItemOrder(InvTweaksHandlerSorting.java:561)
    at invtweaks.InvTweaksHandlerSorting.<init>(InvTweaksHandlerSorting.java:91)
    at invtweaks.InvTweaks.handleSorting(InvTweaks.java:614)
    at invtweaks.InvTweaks.onSortingKeyPressed(InvTweaks.java:257)
    at invtweaks.InvTweaks.onTick(InvTweaks.java:513)
    at invtweaks.InvTweaks.onTickInGame(InvTweaks.java:193)
    at invtweaks.forge.ClientProxy.onTick(ClientProxy.java:65)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_396_ClientProxy_onTick_ClientTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:339)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Kobata** [comment]
I'm guessing another mod somewhere is overwriting the API files with an older (pre-1.9) version.
