### ISSUE TITLE
Something broken?

### ISSUE THREAD

**Issue by labpaw** [Inventory-Tweaks/inventory-tweaks#48]
2013-05-09 08:13:51 [WARNING] [inventorytweaks] java.lang.NullPointerException
    at invtweaks.forge.ForgeItemTreeListener.onTreeLoaded(ForgeItemTreeListener.java:46)
    at invtweaks.InvTweaksItemTreeLoader.addOnLoadListener(InvTweaksItemTreeLoader.java:87)
    at invtweaks.forge.ClientProxy.postInit(ClientProxy.java:49)
    at invtweaks.forge.InvTweaksMod.postInit(InvTweaksMod.java:41)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:494)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:165)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:98)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:695)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:206)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:447)
    at net.minecraft.client.MinecraftAppletImpl.func_71384_a(SourceFile:56)
    at net.minecraft.client.Minecraft.run(Minecraft.java:732)
    at java.lang.Thread.run(Unknown Source)

I got this in console. Forge 689, InvTweaks v1.54b, MC 1.5.2, 79 mods installed.

**Comment by Kobata** [comment]
If I had to guess I'd say a mod is adding an item as a tool in a strange way, just set enableForgeTreeAdditions=false in the config.

**Comment by labpaw** [comment]
Okay thanks. Problem is gone.

**Comment by InsaneJ** [comment]
The error no longer appears during game startup. Thank you :)
