### ISSUE TITLE
1.11.2 Crash when interacting with item - right mouse click

### ISSUE THREAD

**Issue by theArthuryus** [Inventory-Tweaks/inventory-tweaks#481]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Default Options (DefaultOptions_1.11.2-8.2.2.jar)
  CoFH Loading Plugin (CoFHCore-1.11.2-4.2.5.11-universal.jar)
  LoadingPlugin (Quark-r1.2-93.jar)
  ForgelinPlugin (Forgelin-1.5.0.jar)
  RebornCoreASM (RebornCore-1.11.2-2.16.1.115-universal.jar)
  CTMCorePlugin (CTM-MC1.10.2-0.1.0.8.jar)
  CCLCorePlugin (CodeChickenLib-1.11.2-3.0.0.274-universal.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.6.jar)
  NEICorePlugin (NotEnoughItems-1.11.2-2.3.0.227-universal.jar)
  HammerCoreCore (HammerCore_1.11.2-1.8.9.jar)
  LoadingPlugin (ResourceLoader-MC1.11.2-1.5.2.jar)
  CoreMod (Aroma1997Core-1.11.2-1.2.0.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.62.jar)
  IC2core (industrialcraft-2-2.7.74-ex111.jar)
  BookshelfLoadingPlugin (Bookshelf-1.11.2-2.0.0.388.jar)
  MalisisCorePlugin (malisiscore-1.11.2-5.2.1.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 7/7/17 9:59 PM
Description: Unexpected error

java.lang.NoSuchMethodError: invtweaks.api.IItemTreeItem.getExtraData()Lnet/minecraft/nbt/NBTTagCompound;
	at invtweaks.InvTweaksItemTreeItem.equals(InvTweaksItemTreeItem.java:75)
	at invtweaks.InvTweaksItemTreeCategory.contains(InvTweaksItemTreeCategory.java:31)
	at invtweaks.InvTweaksItemTreeCategory.contains(InvTweaksItemTreeCategory.java:37)
	at invtweaks.InvTweaksItemTreeCategory.contains(InvTweaksItemTreeCategory.java:37)
	at invtweaks.InvTweaksItemTreeCategory.contains(InvTweaksItemTreeCategory.java:37)
	at invtweaks.InvTweaksItemTreeCategory.contains(InvTweaksItemTreeCategory.java:37)
	at invtweaks.InvTweaksItemTree.matches(InvTweaksItemTree.java:95)
	at invtweaks.InvTweaksConfig.isAutoRefillEnabled(InvTweaksConfig.java:330)
	at invtweaks.InvTweaks.handleAutoRefill(InvTweaks.java:657)
	at invtweaks.InvTweaks.onTickInGame(InvTweaks.java:207)
	at invtweaks.forge.ClientProxy.onTick(ClientProxy.java:64)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_725_ClientProxy_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1645)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at invtweaks.InvTweaksItemTreeItem.equals(InvTweaksItemTreeItem.java:75)
	at invtweaks.InvTweaksItemTreeCategory.contains(InvTweaksItemTreeCategory.java:31)
	at invtweaks.InvTweaksItemTreeCategory.contains(InvTweaksItemTreeCategory.java:37)
	at invtweaks.InvTweaksItemTreeCategory.contains(InvTweaksItemTreeCategory.java:37)
	at invtweaks.InvTweaksItemTreeCategory.contains(InvTweaksItemTreeCategory.java:37)
	at invtweaks.InvTweaksItemTreeCategory.contains(InvTweaksItemTreeCategory.java:37)
	at invtweaks.InvTweaksItemTree.matches(InvTweaksItemTree.java:95)
	at invtweaks.InvTweaksConfig.isAutoRefillEnabled(InvTweaksConfig.java:330)
	at invtweaks.InvTweaks.handleAutoRefill(InvTweaks.java:657)
	at invtweaks.InvTweaks.onTickInGame(InvTweaks.java:207)
	at invtweaks.forge.ClientProxy.onTick(ClientProxy.java:64)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_725_ClientProxy_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343)

**Comment by Kobata** [comment]
Try removing other mods (particularly ones with jars that start with letters before 'I')

It looks like *someone* was a bad person and left an old copy of something inside their jar that likely shouldn't be there.

**Comment by theArthuryus** [comment]
hey thanks! doing the old'process of elimination I have found that the forestry mod was bugged, found that there was an update and it worked. Thanks again!
