### ISSUE TITLE
java.util.NoSuchElementException: packet_handler when vanilla client joins

### ISSUE THREAD

**Issue by BrainStone** [Inventory-Tweaks/inventory-tweaks#490]
**Minecraft Version: 1.12**
**Inventory Tweaks Version: InventoryTweaks-1.63+beta.107.jar**

When a vanilla client joins they get kicked from the server right when they join and in the server console this error pops up.

```
[13:56:02] [Server thread/WARN]: Failed to handle packet for /x.x.x.x:xxxxx
java.util.NoSuchElementException: packet_handler
        at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1080) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:251) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:240) ~[DefaultChannelPipeline.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.insertIntoChannel(NetworkDispatcher.java:176) ~[NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.serverToClientHandshake(NetworkDispatcher.java:163) ~[NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.fmlServerHandshake(FMLNetworkHandler.java:72) ~[FMLNetworkHandler.class:?]
        at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:135) ~[pa.class:?]
        at net.minecraft.server.network.NetHandlerLoginServer.func_73660_a(NetHandlerLoginServer.java:63) ~[pa.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179) [ox.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:784) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:391) [nx.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[13:56:03] [Server thread/INFO]: The_BrainStone lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.io.IOException: Can't serialize unregistered packet
```

**Comment by ghost** [comment]
Confirmed; happening with Inventory Tweaks 1.63 [R].
Removed Inventory Tweaks, no more serialize unregistered packet errors.
