### ISSUE TITLE
java.lang.NullPointerException at invtweaks.InvTweaksHandlerSorting.sortWithRules

### ISSUE THREAD

**Issue by gelonsoft** [Inventory-Tweaks/inventory-tweaks#540]
**Minecraft Version: 1.12.2 (forge-1.12.2-14.23.2.2634)**
**Inventory Tweaks Version: InventoryTweaks-1.64-dev.jar**
Modpack: FTB Modern Skyblock 3 ver. 3.2.0.1

[Logs.zip](https://github.com/Inventory-Tweaks/inventory-tweaks/files/1866319/Logs.zip)

> 

[15:57:03] [main/ERROR]: InvTweaks: [ERROR] [3] Failed to sort container: null (l203 in HandlerSorting.java)
java.lang.NullPointerException: null
	at invtweaks.InvTweaksHandlerSorting.sortWithRules(InvTweaksHandlerSorting.java:203) ~[InvTweaksHandlerSorting.class:?]
	at invtweaks.InvTweaksHandlerSorting.sort(InvTweaksHandlerSorting.java:155) ~[InvTweaksHandlerSorting.class:?]
	at invtweaks.InvTweaksGuiSortingButton.func_146116_c(InvTweaksGuiSortingButton.java:69) [InvTweaksGuiSortingButton.class:?]
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:435) [blk.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:323) [bmg.class:?]
	at org.cyclops.cyclopscore.client.gui.container.ScrollingGuiContainer.func_73864_a(ScrollingGuiContainer.java:127) [ScrollingGuiContainer.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533) [blk.class:?]
	at org.cyclops.cyclopscore.client.gui.container.ScrollingGuiContainer.func_146274_d(ScrollingGuiContainer.java:111) [ScrollingGuiContainer.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501) [blk.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757) [bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[15:57:03] [main/INFO]: [CHAT] InvTweaks: [ERROR] [3] Failed to sort container: null (l203 in HandlerSorting.java)
`

**Comment by Szasdragon** [comment]
Seems like the item container which you try to sorting not supported. Try [this](http://inventory-tweaks.readthedocs.io/en/latest/#adding-configured-compatibility-info)! And please describe your problem, not dumping logs. I'm not java expert, but try to help.
