### ISSUE TITLE
Latest dev builds and Galacticraft.

### ISSUE THREAD

**Issue by Divinder** [Inventory-Tweaks/inventory-tweaks#56]
Getting the following crash with only latest Galacticraft, Inventorytweak 1.55-dev build 32 and forge 7.8.0.725, I may have missed something you posted earlier saying this would happen, if so sorry for wasting time.

[SEVERE] [ForgeModLoader] Caught exception from inventorytweaks
java.lang.NoSuchFieldError: CREATIVE_MAIN_INVENTORY_SIZE
    at invtweaks.InvTweaksObfuscation.<init>(InvTweaksObfuscation.java)
    at invtweaks.InvTweaks.<init>(InvTweaks.java:88)
    at invtweaks.forge.ClientProxy.init(ClientProxy.java:41)
    at invtweaks.forge.InvTweaksMod.init(InvTweaksMod.java:42)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:494)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:186)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:166)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:103)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:213)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:448)
    at net.minecraft.client.MinecraftAppletImpl.func_71384_a(SourceFile:56)
    at net.minecraft.client.Minecraft.run(Minecraft.java:733)
    at java.lang.Thread.run(Unknown Source)

**Comment by Kobata** [comment]
Error in galacticraft, attempting to inject a change to a variable that doesn't exist.

(You can't really trust where it 'appears' to come from when coremods are involved.)
