### ISSUE TITLE
InvTweaks: [ERROR] [6] Failed to trigger shortcut

### ISSUE THREAD

**Issue by dblack850** [Inventory-Tweaks/inventory-tweaks#611]
**Minecraft Version:** 1.12.2
**Inventory Tweaks Version:** 1.63
**Modpack:** "[The 1.12.2 Pack](https://the-1122-pack.com/mods)"

Trying to Shift + Click to 'craft all' but only get the base stack. Friend don't seem to be having the issue and I didn't either with the other modpack we were using but, if anyone can help me, I would really appreciate it.

The message I get in chat, sometimes but not every time, is:
```
[Client thread/ERROR] [inventorytweaks]: InvTweaks: [ERROR] [6] Failed to trigger shortcut: Index: -1, Size: 9
```

In my latest.log, the last error I got from it was:
```
java.lang.IndexOutOfBoundsException: Index: -1, Size: 9
	at java.util.ArrayList$SubList.rangeCheck(Unknown Source) ~[?:1.8.0_231]
	at java.util.ArrayList$SubList.get(Unknown Source) ~[?:1.8.0_231]
	at invtweaks.container.DirectContainerManager.getSlot(DirectContainerManager.java:281) ~[DirectContainerManager.class:?]
	at invtweaks.container.DirectContainerManager.move(DirectContainerManager.java:74) ~[DirectContainerManager.class:?]
	at invtweaks.InvTweaksHandlerShortcuts.runShortcut(InvTweaksHandlerShortcuts.java:370) ~[InvTweaksHandlerShortcuts.class:?]
	at invtweaks.InvTweaksHandlerShortcuts.handleShortcut(InvTweaksHandlerShortcuts.java:106) [InvTweaksHandlerShortcuts.class:?]
	at invtweaks.InvTweaks.handleShortcuts(InvTweaks.java:958) [InvTweaks.class:?]
	at invtweaks.InvTweaks.onTickInGUI(InvTweaks.java:241) [InvTweaks.class:?]
	at invtweaks.forge.ClientProxy.onTick(ClientProxy.java:62) [ClientProxy.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2566_ClientProxy_onTick_ClientTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344) [FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1708) [bib.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

Forgive me if I don't give enough information, I'm relatively new to Minecraft and certainly to playing with modpacks but catch on quick and had this set up by someone else. If more info is needed, let me know!

**Comment by dblack850** [comment]
This worked fine with turning wood into planks but not stone into bricks and not granite into polished granite.

I closed because I thought I had made a mistake but it seems something is going on, at least for me or compatibility with a mod in this pack, maybe.

Edit: Shift + Click'ing the '+' worked, rather than Shift + Click'ing the final product, like I had been doing in the other pack. Gonna continue to test and be sure.
