### ISSUE TITLE
Too Many Items Incompatibility 

### ISSUE THREAD

**Issue by trobb20** [Inventory-Tweaks/inventory-tweaks#64]
When i go into survival mode, after having just inventory tweaks, and Too many items installed the game crashes. here is my report

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 7/9/13 12:11 PM
Description: Unexpected error

java.lang.IllegalAccessError: tried to access field net.minecraft.client.gui.inventory.GuiContainer.field_74198_m from class invtweaks.InvTweaksObfuscation
    at invtweaks.InvTweaksObfuscation.getGuiX(InvTweaksObfuscation.java:160)
    at invtweaks.InvTweaks.handleGUILayout(InvTweaks.java:760)
    at invtweaks.InvTweaks.onTickInGUI(InvTweaks.java:139)
    at invtweaks.forge.ForgeClientTick.tickEnd(ForgeClientTick.java:43)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:141)
    at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:367)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1956)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:898)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:826)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:57)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:18)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at invtweaks.InvTweaksObfuscation.getGuiX(InvTweaksObfuscation.java:160)
    at invtweaks.InvTweaks.handleGUILayout(InvTweaks.java:760)
    at invtweaks.InvTweaks.onTickInGUI(InvTweaks.java:139)
    at invtweaks.forge.ForgeClientTick.tickEnd(ForgeClientTick.java:43)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:141)
    at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:367)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['trddd'/54, l='MpServer', x=47.39, y=97.12, z=45.08]]
    Chunk stats: MultiplayerChunkCache: 441
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-2,94,-341), Chunk: (at 14,5,11 in -1,-22; contains blocks -16,0,-352 to -1,255,-337), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
    Level time: 1919184 game time, 1545021 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 31 total; [EntityPainting['Painting'/68, l='MpServer', x=78.50, y=76.00, z=17.06], EntityPainting['Painting'/69, l='MpServer', x=87.94, y=76.00, z=52.00], EntityPainting['Painting'/70, l='MpServer', x=87.94, y=83.00, z=51.00], EntityPainting['Painting'/70, l='MpServer', x=87.94, y=83.00, z=51.00], EntityPainting['Painting'/71, l='MpServer', x=109.06, y=83.00, z=46.00], EntityPainting['Painting'/64, l='MpServer', x=43.50, y=83.00, z=53.94], EntityPainting['Painting'/67, l='MpServer', x=67.50, y=76.00, z=17.06], EntityPainting['Painting'/76, l='MpServer', x=109.06, y=76.00, z=71.00], EntityPainting['Painting'/77, l='MpServer', x=109.06, y=76.00, z=69.00], EntityPig['Pig'/78, l='MpServer', x=125.39, y=77.00, z=23.50], EntityPainting['Painting'/71, l='MpServer', x=109.06, y=83.00, z=46.00], EntityPainting['Painting'/72, l='MpServer', x=109.06, y=83.00, z=43.00], EntityPainting['Painting'/73, l='MpServer', x=109.06, y=83.00, z=40.00], EntityPainting['Painting'/74, l='MpServer', x=109.06, y=83.00, z=51.00], EntityPainting['Painting'/75, l='MpServer', x=109.06, y=83.00, z=48.50], EntityPainting['Painting'/67, l='MpServer', x=67.50, y=76.00, z=17.06], EntityPainting['Painting'/64, l='MpServer', x=43.50, y=83.00, z=53.94], EntityPainting['Painting'/69, l='MpServer', x=87.94, y=76.00, z=52.00], EntityPainting['Painting'/68, l='MpServer', x=78.50, y=76.00, z=17.06], EntityPainting['Painting'/72, l='MpServer', x=109.06, y=83.00, z=43.00], EntityPainting['Painting'/73, l='MpServer', x=109.06, y=83.00, z=40.00], EntityPig['Pig'/59, l='MpServer', x=3.03, y=90.00, z=101.97], EntityPainting['Painting'/74, l='MpServer', x=109.06, y=83.00, z=51.00], EntitySheep['Sheep'/58, l='MpServer', x=0.25, y=81.00, z=40.22], EntityPainting['Painting'/75, l='MpServer', x=109.06, y=83.00, z=48.50], EntityClientPlayerMP['trddd'/54, l='MpServer', x=47.39, y=97.12, z=45.08], EntityPainting['Painting'/76, l='MpServer', x=109.06, y=76.00, z=71.00], EntityPainting['Painting'/77, l='MpServer', x=109.06, y=76.00, z=69.00], EntityCow['Cow'/63, l='MpServer', x=32.31, y=74.00, z=29.22], EntityCow['Cow'/61, l='MpServer', x=30.78, y=85.00, z=101.22], EntitySheep['Sheep'/60, l='MpServer', x=17.94, y=87.00, z=96.16]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:440)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2298)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:851)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:57)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:18)

-- System Details --
Details:
    Minecraft Version: 1.6.2
    Operating System: Mac OS X (x86_64) version 10.8.4
    Java Version: 1.6.0_51, Apple Inc.
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
    Memory: 36090864 bytes (34 MB) / 232611840 bytes (221 MB) up to 1568538624 bytes (1495 MB)
    JVM Flags: 1 total; -Xmx1500m
    AABB Pool Size: 363 (20328 bytes; 0 MB) allocated, 153 (8568 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 63
    FML: MCP v8.04 FML v6.2.16.784 Minecraft Forge 9.10.0.784 5 mods loaded, 5 mods active
    mcp{8.04} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{6.2.16.784} [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{9.10.0.784} [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TooManyItems{1.6.2} [TooManyItems](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inventorytweaks{1.55} [Inventory Tweaks](InventoryTweaks-MC1.6.2-1.55-b56.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Launched Version: 1.6.2-Forge9.10.0.784
    LWJGL: 2.9.0
    OpenGL: NVIDIA GeForce 320M OpenGL Engine GL version 2.1 NVIDIA-8.12.47 310.40.00.05f01, NVIDIA Corporation
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Pack: oCd pack 1
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 327 (18312 bytes; 0 MB) allocated, 26 (1456 bytes; 0 MB) used

What is going on? is it the fact tmi adds the option to add items that you cannot get normally?

**Comment by Kobata** [comment]
Go tell the TMI guy to stop wholesale replacing classes, or at least to make everything in them public if he is.

**Comment by trobb20** [comment]
So basically there is no way that this can be fixed until TMI can stop wholesale replacing classes?
