### ISSUE TITLE
Minecraft not starting when InventoryTweaks enabled

### ISSUE THREAD

**Issue by ronnierap** [Inventory-Tweaks/inventory-tweaks#71]
Somehow when Inventory tweaks is loaded the Minecraft client does not startup.

Using the following Components
- MagicLauncher 1.1.6

Mods: 
- minecraftforge-universal-1.6.2-9.10.0.789
- InventoryTweaks-MC1.6.2-1.55-b56

It is a clean minecraft install and selected the 1.6.2 version

This works:
![screen shot 2013-07-16 at 10 20 48](https://f.cloud.github.com/assets/1546947/803405/aad0b9bc-edf0-11e2-9aab-490bcc674a10.png)

This crashes the client
![screen shot 2013-07-16 at 10 21 00](https://f.cloud.github.com/assets/1546947/803409/b7daac4e-edf0-11e2-86e4-5240cfc99704.png)

---- Minecraft Crash Report ----
// Oops.

Time: 7/16/13 10:14 AM
Description: Initializing game

java.lang.NullPointerException
    at bka.b(SourceFile:76)
    at ats.O(SourceFile:332)
    at ats.d(SourceFile:599)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at magic.launcher.Launcher.main(Unknown Source)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at bka.b(SourceFile:76)
    at ats.O(SourceFile:332)

-- Initialization --
Details:
Stacktrace:
    at ats.d(SourceFile:599)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at magic.launcher.Launcher.main(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.6.2
    Operating System: Mac OS X (x86_64) version 10.9
    Java Version: 1.6.0_51, Apple Inc.
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
    Memory: 481778608 bytes (459 MB) / 530186240 bytes (505 MB) up to 530186240 bytes (505 MB)
    JVM Flags: 2 total; -Xms512m -Xmx512m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: No suspicious classes found.
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    Launched Version: 1.6.2
    LWJGL: 2.9.0
    OpenGL: AMD Radeon HD 6770M OpenGL Engine GL version 2.1 ATI-1.12.42, ATI Technologies Inc.
    Is Modded: Very likely; Jar signature invalidated
    Type: Client (map_client.txt)
    Resource Pack: Default
    Current Language: ~~ERROR~~ NullPointerException: null
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null

**Comment by ChrisLane** [comment]
You need invtweaks in the external mods section.

**Comment by Kobata** [comment]
Forge is not installed correctly, use the installer and the Forge profile it creates as the base for adding mods.

**Comment by ronnierap** [comment]
Thanks for your support and Feedback: while the Forge plugin was able to load this way, prior to 1.6. Indeed you now have to install it and use the Forge profile.
Then by adding invtweaks to the mods folder works.. 

This renders the use for MagicLauncher quit useless in my opinion. I used to to connect to 1.4, 1.5 and now 1.6 servers. I'll need to write them (or him).

Thanks again.
