### ISSUE TITLE
Inv tweaks will not load when using magic launcher with up to date forge

### ISSUE THREAD

**Issue by kyleboze** [Inventory-Tweaks/inventory-tweaks#89]
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 8/3/13 9:23 PM
Description: Initializing game

java.lang.NullPointerException
    at bka.b(SourceFile:76)
    at ats.O(SourceFile:332)
    at ats.d(SourceFile:599)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at magic.launcher.Launcher.main(Unknown Source)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at bka.b(SourceFile:76)
    at ats.O(SourceFile:332)

-- Initialization --
Details:
Stacktrace:
    at ats.d(SourceFile:599)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at magic.launcher.Launcher.main(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.6.2
    Operating System: Mac OS X (x86_64) version 10.7.5
    Java Version: 1.6.0_51, Apple Inc.
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
    Memory: 263498272 bytes (251 MB) / 310640640 bytes (296 MB) up to 310640640 bytes (296 MB)
    JVM Flags: 2 total; -Xms300m -Xmx300m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: No suspicious classes found.
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    Launched Version: 1.6.2
    LWJGL: 2.9.0
    OpenGL: NVIDIA GeForce 9400 OpenGL Engine GL version 2.1 NVIDIA-7.32.12, NVIDIA Corporation
    Is Modded: Very likely; Jar signature invalidated
    Type: Client (map_client.txt)
    Resource Pack: Monkeyfarms_Custom-John_Smith-RESOURCE_PACK
    Current Language: ~~ERROR~~ NullPointerException: null
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null

**Comment by Kobata** [comment]
Don't use magic launcher if you don't know how to make it install things correctly. (It's not easy in 1.6)
